### ISSUE TITLE
How to make one field depend on another field?

### ISSUE THREAD

**Issue by eastglow** [naver/fixture-monkey#1033]
안녕하세요. 픽스쳐몽키 사용 중에 하나 궁금한 점이 있어 질문드립니다.

```
TestEnum {
    A,
    B
}

TestDto {
    private TestEnum testEnum;
    private String test;
}
```

이런 구조의 TestDto를 테스트 객체로 생성할 때, testEnum 값에 따라서 test 필드의 값 세팅을 제어할 수 있는 방법이 궁금합니다.

예를 들어, testEnum이 A라면 test 필드엔 a가 세팅되어야 하고 B라면 test 필드엔 b가 세팅되게 하려는 의도입니다.

즉, 한 필드가 다른 필드에 의존성을 가지게 하여 값이 세팅되도록 하고 싶습니다.

**Comment by flex-myeonghyeon** [comment]
thenApply 또는 acceptIf 를 참고하시면 될거 같습니다
https://naver.github.io/fixture-monkey/v1-0-0-kor/docs/customizing-objects/apis/#thenapply

**Comment by flex-myeonghyeon** [comment]
thenApply 는 아래와 같이 작성할 수 있습니다

```java
fixtureMonkey.giveMeBuilder(Product.class)
    .thenApply((it, builder) -> 
        if (it.getTestEnum() == A) {
            builder.set("test", "a");   
        } else if (it.getTestEnum() == B) {
            builder.set("test", "b");  
        }
    }
```

위와 같은 케이스에서는 acceptIf 가 좀 더 편리합니다

```java
fixtureMonkey.giveMeBuilder(Product.class)
    .acceptIf(
        it -> it.getTestEnum() == A,
        builder.set("test", "a")
    )
    .acceptIf(
        it -> it.getTestEnum() == B,
        builder.set("test", "b")
    )
}
```

**Comment by eastglow** [comment]
@flex-myeonghyeon 
아, 저런 커스터마이징이 있었군요. docs 내 다른 부분에서만 찾아봤었네요..^^; 감사합니다.

**Comment by eastglow** [comment]
@flex-myeonghyeon 

안녕하세요. thenApply, acceptIf에 대헤 추가로 궁금한 점이 있어 코멘트를 남깁니다.

공식 docs에서도 둘 사이에 명확한 차이점이나 어느 상황에 써야한다 와 같은 내용은 없던데 하나의 필드에 대해서 커스텀이 필요할 때는 둘 중 어느 것을 써도 무방할 듯 하더라고요. 다만, 조건 로직이 복잡하거나 n개의 필드를 한번에 커스텀할 때는 thenApply가 더 사용하기는 편해보이긴 합니다. (내부적으로 로직을 봤을 때도 acceptIf는 thenApply를 호출하는 것으로 보이구요.)

혹시 이 두개에 대해서 어떤 상황에 쓰는게 좋다 혹은 쓰면 안 된다 라는게 있는지 궁금합니다. 제가 조금 써보았을 때는 사실 둘 중 어느 것을 사용해서 커스터마이징을 해도 같은 거 같아서 문의드려요.

**Comment by flex-myeonghyeon** [comment]
@eastglow 
네 설명해주신 정도의 차이점이 전부라서 어느것을 사용해도 무관합니다 (동일한 논리로 동작합니다)

acceptIf 는 1가지 if 조건 판단으로 customize 하는 경우에 thenApply 보다 표현력이나 사용 편의성이 조금 더 있다  정도의 장점이 있고
if / else if / else 등 복합적인 컨디션에 따라 customize 해야 되는 경우에는 thenApply 가 적합할거 같습니다

**Comment by eastglow** [comment]
@flex-myeonghyeon 

답변 감사합니다!
