### ISSUE TITLE
When using Generic, what happens if size() and thenApply() are used together?

### ISSUE THREAD

**Issue by eastglow** [naver/fixture-monkey#1041]
## Describe your question
안녕하세요. fixture monkey에서 generic을 받는 필드를 가진 클래스를 생성하는 경우에 의도했던 것과 다르게 동작하는 부분이 있어서 잘못 사용하고 있는건지, 아니면 픽스쳐 몽키에서 의도된 동작인지 궁금하여 질문 남깁니다.

```
public class MainDto {

	private PageDto<DataDto> data;
}

public class PageDto<T> {

    private List<T> resultList;
    private int curPage;
    private int pageSize;
    private int totalCount;
}

public class DataDto {

	private String field1;
	private int field2;
}

FixtureMonkey fixtureMonkey = FixtureMonkey.builder()
	.defaultNotNull(true)
	.register(
		MainDto.class,
		fixture -> fixture.giveMeBuilder(MainDto.class)
	)
	.register(
		PageDto.class,
		fixture -> fixture.giveMeBuilder(PageDto.class)
			.minSize("resultList", 1)
			.thenApply(
				(it, builder) -> builder.set("totalCount", it.getResultList().size())
			)
			.set("curPage", 1)
			.set("pageSize", 10)
	)
	.register(
		DataDto.class,
		fixture -> fixture.giveMeBuilder(DataDto.class)
			.set(javaGetter(DataDto::getField1), Arbitraries.strings().numeric().ofLength(10))
			.set(javaGetter(DataDto::getField2), Arbitraries.integers().greaterOrEqual(1))
	)
	.build();

MainDto mockResponse = fixtureMonkey.giveMeOne(MainDto.class);
```

위와 같이 MainDto를 빌더로 생성하면 제가 기대했던 것은, "MainDto의 PageDto<DataDto> data 필드 List 요소들은 위 DataDto의 register 규약들에 맞춰서 생성될 것이다" 였는데요,

생성된 객체를 디버깅해보면 PageDto의 다른 필드들은 제가 설정해둔 규약에 맞게 들어가있는데(ex. curPage = 1) generic로 받는 DataDto의 경우, minSize는 1개 이상으로 잘 생성되고 totalCount도 thenApply()의 설정처럼 resultList size만큼 잘 할당되지만 실제 생성된 List<DataDto>를 살펴보면 DataDto.class에 걸어둔 규약들이 적용되지 않았습니다.

그래서 무엇이 영향을 주는지 찾다보니 PageDto에 있는 thenApply를 제거하고 돌려보니 그때서야 DataDto의 값들은 저 규약에 맞게 생성이 되던데요, 혹시 이 과정에서 잘못 사용하고 있는 옵션이 있거나 제가 놓친 부분이 있을지 질문드립니다.

**Comment by seongahjo** [comment]
@eastglow 
안녕하세요. 

주신 예제에서 PageDto를 register로 등록할 때 사용하신 타입이 제네릭이 없는 raw type입니다.
`register(PageDto.class, ...)` 

이 때문에 타입 정보가 유실돼서 DataDto의 register 정보가 적용이 안된 걸로 보입니다.
아래와 같이 제네릭 정보를 같이 넣어주시면 의도대로 동작할 것 같습니다.

```
.register(
    new MatcherOperator<>(
	    p -> p.getAnnotatedType().equals(new TypeReference<PageDto<DataDto>>() {
	    }.getAnnotatedType()),
	    fixture -> fixture.giveMeBuilder(
			    new TypeReference<PageDto<DataDto>>() {
			    }
		    )
		    .minSize("resultList", 1)
		    .thenApply(
			    (it, builder) -> builder.set("totalCount", it.getResultList().size()) // register 정보가 없음
		    )
		    .set("curPage", 1)
		    .set("pageSize", 10)
    )
  )
```

문서에 해당 내용 보충하도록 하겠습니다. 감사합니다.

혹시 위와 같이 옵션을 변경했는데도 안되시면 말씀해주세요.

감사합니다.

**Comment by seongahjo** [comment]
@eastglow 
앗, 죄송합니다. 제가 순간 착각해서 잘못 알려드렸군요;

아래와 같이 조건을 type간 비교로 바꾸시면 의도대로 동작합니다.

```
.register(
  new MatcherOperator<>(
		  p -> p.getAnnotatedType().getType().equals(new TypeReference<PageDto<DataDto>>() {
		  }.getAnnotatedType().getType()),
		  fixture -> fixture.giveMeBuilder(
						  new TypeReference<PageDto<DataDto>>() {
						  }
				  )
				  .minSize("resultList", 1)
				  .thenApply(
						  (it, builder) -> builder.set("totalCount", it.getResultList().size())
				  )
				  .set("curPage", 1)
				  .set("pageSize", 10)
    )
  )
```

<img width="395" alt="image" src="https://github.com/user-attachments/assets/9c7ec734-f552-4891-b111-e4695c873595">


확인하고 이슈 있으시면 알려주세요.

감사합니다.

**Comment by eastglow** [comment]
@seongahjo 

다시 주신 답변대로 getType()을 호출해서 builder를 구성하니 잘 동작하네요! 답변 감사합니다.
