### ISSUE TITLE
FailoverIntrospector의 enableLoggingFail 옵션을 Introspector들에도 적용할수있을까요?

### ISSUE THREAD

**Issue by HanJaehee** [naver/fixture-monkey#1066]
## Describe the feature you request
1.0.27에서 `enableLoggingFail` 옵션이 추가되어서 `FailoverIntrospector` 자체에서 발생하는 warning 로그들은 조절이 가능한 상태인데요.
FailoverIntrospector에 넣는 Introspector들에도 위 옵션을 승계할수있을지 궁금합니다.

## If the feature request is approved, would you be willing to submit a PR?
*Yes  (Help can be provided if you need assistance submitting a PR)*

**Comment by seongahjo** [comment]
@HanJaehee  님, 안녕하세요.

> FailoverIntrospector에 넣는 Introspector들에도 위 옵션을 승계할수있을지 궁금합니다.

단시간내에 계획이 없지만, 장기적으로는 로그를 글로벌하게 관리하는 방향으로 진행하려고 계획은 하고 있습니다.
그전에 첫 단계로 이 이슈를 진행해도 좋을 것 같긴 하네요. 작업이 가능하시다면 PR 올려주시면 감사하겠습니다!

감사합니다.

**Comment by IAM20** [comment]
[fixtureMonkey 공식 문서대로 설정](https://naver.github.io/fixture-monkey/v1-0-0-kor/docs/generating-objects/introspector/#failoverarbitraryintrospector) 하여도 WARN 로그가 나서 보니 OR 조건이 추가되어있고 이 이슈로 인해 상황이 벌어지고 있는 것 같습니다.

해당 옵션은 어떻게 사용하면되나요?
