### ISSUE TITLE
Issue with recursive interfaces

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#1083]
## Describe the bug
When I recursive set an object that accepts an interface for some reason fixture monkey is mutating it into an empty list.

This works as expected on version 1.0.28

## Your environment
Fixture Monkey: 1.1.1
Java 17

## Steps to reproduce
https://github.com/esfomeado/fixture-monkey-bug/blob/master/src/test/java/com/example/bug/FixtureMonkeyTest.java#L117

## Expected behaviour
Should set the value as expected.

## Actual behaviour
It´s changing the value to an empty list

**Comment by seongahjo** [comment]
@esfomeado 
Thank you for reporting an issue.
It is fixed in 1.1.2. Please check it out!

**Comment by esfomeado** [comment]
Working as expected.

Thanks
