### ISSUE TITLE
migration guide에 kotlin은 giveMeBuilder를 사용하는 것이 맞나요?

### ISSUE THREAD

**Issue by HanJaehee** [naver/fixture-monkey#1084]
## Describe your question
[migration guide](https://naver.github.io/fixture-monkey/v1-1-0/docs/migration-guide/migration-guide/#how-to-use-kotlin-arbitrarybuilder-apis)에는 kotlin이 `giveMeBuilder`를 사용하도록 안내하고있는것같은데, [코드](fixture-monkey-kotlin/src/main/kotlin/com/navercorp/fixturemonkey/kotlin/KPropertyExtensions.kt) 상으론 `ArbitraryBuilder`의 `setExp`등의 확장함수들이 deprecated 되어 `giveMeKotlinBuilder`를 사용하라고 되어있어서 질문드립니다!

**Comment by seongahjo** [comment]
@HanJaehee 님 안녕하세요. 확인해주셔서 감사합니다!

`giveMeKotinBuilder`를 사용하는 게 맞습니다. 문서에 반영을 못했군요;
혹시 괜찮으시다면 PR을 올려 변경해주실 수 있을까요??

아래 두 파일을 수정하면 됩니다.
- `docs/content/v1.1.x/docs/migration-guide/migration-guide.md`
- `docs/content/v1.1.x-kor/docs/migration-guide/migration-guide.md`


감사합니다.
