### ISSUE TITLE
중첩 Class 에 대한 Builder 설정 문의

### ISSUE THREAD

**Issue by melong0124** [naver/fixture-monkey#1098]
안녕하세요. 
정말 잘쓰고 있습니다. 
너무 유용한 코드를 공유해 주셔서 감사하게 생각합니다.

만약 

```kotlin
data class ADto(
    val id: Long,
    val b: BDto,
)
```

```kotlin
data class BDto(
    val id: Long,
    val name: String,
)
```

와 같이 정의 되면 ADto 를 생성할 때 Builder 를 설정하고, 

```
 ..... fixtureMonkey
                .giveMeBuilder(BDto::class.java)
                .setExp(BDto::id, Arbitraries.longs().greaterOrEqual(1))
                .minSizeExp(BDto::name, 1)


 ..... fixtureMonkey
                .giveMeBuilder(ADto::class.java)
                .setExp(BDto::id, Arbitraries.longs().greaterOrEqual(1))
```

와 같이 정의 할 때 ADto 객체를 생성할 때 BDto 에 대한 설정값을 받아서 처리하게 할 수 있을까요?

**Comment by seongahjo** [comment]
@melong0124 님 안녕하세요.

잘 사용해주셔서 감사합니다!

주신 질문을 정확하게 이해했는지 모르겠는데, ADto 객체를 생성할 때 BDto의 값을 설정하고 싶다는 걸로 이해했는데 맞을까요?? 아래와 같이 사용하시면 될 것 같습니다.

```kotlin
 fixtureMonkey.giveMeKotlinBuilder<ADto>()
            .setExp(ADto::b into BDto::id, Arbitraries.longs().greaterOrEqual(1))
            .sample()
```


감사합니다.

**Comment by melong0124** [comment]
@seongahjo 님, 답변 감사합니다!

혹시, 개별적 컬럼 설정 말고, BDto 의 builder 자체를 넘겨서 b 가 설정될 떄 해당 builder 의 설정대로 생성될 수 있을까요?

**Comment by seongahjo** [comment]
@melong0124 님 안녕하세요.

경우에 따라 해결법이 다른데요.
만약 모든 `ADto` 필드 `BDto` 타입이 공통된 연산을 사용하는 경우를 말씀하시는 거라면 다음 옵션을 사용하시면 됩니다. [register](https://naver.github.io/fixture-monkey/v1-1-0-kor/docs/fixture-monkey-options/customization-options/#%ED%8A%B9%EC%A0%95-%ED%83%80%EC%9E%85%EC%97%90-%EA%B8%B0%EB%B3%B8-arbitrarybuilder-%EB%93%B1%EB%A1%9D%ED%95%98%EA%B8%B0)

그게 아니고 특정 테스트 케이스에서만 해당 설정이 필요하시다면 다음 API를 참조하시면 될 것 같습니다.

[thenApply](https://naver.github.io/fixture-monkey/v1-1-0-kor/docs/customizing-objects/apis/#%EC%83%98%ED%94%8C%EB%A7%81-%EA%B2%B0%EA%B3%BC%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%B4-%EC%B6%94%EA%B0%80-%EC%BB%A4%EC%8A%A4%ED%84%B0%EB%A7%88%EC%9D%B4%EC%A7%95%ED%95%98%EA%B8%B0)

감사합니다.

**Comment by melong0124** [comment]
답변 감사합니다. :)
