### ISSUE TITLE
Add ExTree Third-party Module for expression

### ISSUE THREAD

**Issue by mhyeon-lee** [naver/fixture-monkey#32]
https://github.com/streamx-co/ExTree
https://github.com/TrigerSoft/jaque#java-query

**Comment by seongahjo** [comment]
ExTree 사용을 고려해봤는데요, 다음과 같은 두 가지 요소에 대한 검토가 필요할 것 같습니다.
1. 라이센스
2. 성능

만약 라이센스에 문제가 없다면 일단 사용해보고 성능을 판단하는 게 좋아 보입니다.
성능에 문제가 있다면 필요한 부분만 직접 구현해서 사용하는 게 좋을 것 같습니다.
지금은 ASM에 익숙하지 않아, 직접 구현하는 건 비용이 너무 큰 것 같고 모듈을 만들어 익숙해진 후에 직접 구현할 예정입니다.

최종적으로는 이 모듈을 직접 구현하는 걸 생각하고 있습니다.
ExTree의 동작 구조를 정확히 알지는 못하지만 예상했을 때 Vritual Class Tree를 만드는 과정과 ExTree의 동작을 하나로 합칠 수 있을 것 같습니다.

**Comment by mhyeon-lee** [comment]
@seongahjo 넵 우선은 참고용으로 기록해놨습니다.
ExTree 를 사용하게 되면 해당 모듈은 별도로 구성하고 그 모듈은 GPL 라이센스를 따라야 될거 같습니다.

Expression 의 컴파일 체크 및 자동완성을 지원할 방식을 고려중인데요
ExTree 와 같은 방식과 QueryDsl 과 같이 Generation 하는 방법 등 어느것이 좋을지 고민이 되긴합니다.

우선 ExTree 를 고려했을 땐 사용자 입장에서 아래와 같은 방식의 지원을 생각했는데, @seongahjo 님은 어떤 방식을 생각했나요?

---
```java
fixture.giveMeBuilder(Person.class)
    .set("friend.name", "john")
     .sample()
```

여기서 표현식인 "friend.name" 을 ExTree 를 사용해서 만들도록 지원합니다.

```java
fixture.giveMeBuilder(Person.class)
    .set(ex(Person::getFriend, Friend::getName()), "john")
     .sample()
```

QueryDSL 과 같이 모델 Generation 방식을 사용하게 되면 아래와 같을 겁니다.
표현식이나 사용 방식이 직관적이고 간단하긴 하지만, 모델 Generation 을 해줘야 한다는 단점이 있습니다.
```java
fixture.giveMeBuilder(Person.class)
    .set(FPerson.friend.name, "john")
     .sample()
```

**Comment by seongahjo** [comment]
@mhyeon-lee 
모듈 별로 라이센스 정책을 다르게 가져갈 수 있나요?
가져갈 수 있다면 말씀하신 것 처럼 GPL 라이센스로 명시해야 겠군요.
해당 모듈에 LICENSE 파일을 추가하면 되는 걸까요?

--- 

저는 exTree를 사용하는 방식을 생각했습니다. 아직 정확히 exTree에 대해 보지 않았지만 다음과 같이 쓸 수 있을 것 같습니다.
```java
fixture.giveMeBuilder(Person.class)
    .set((Person p) -> p.getFriend().getName(), "john")
    .sample()
```

QueryDSL을 잠깐 사용해봐서 정확히는 모르는데요, QueryDSL 방법을 사용하면 모델을 만들어주는 별도의 플러그인이 있어야하는 걸로 알고 있습니다. 플러그인도 별도로 만들어야하고, 사용도 번거롭지 않나 싶습니다.
제일 큰 문제는, 필드명 변경 탐지는 가능하지만 IDE의 refactor 기능과 연동은 안될 것 같군요.

표현식이 가지는 단점이 두 가지라고 생각하는데요.
1. 자동 완성 미지원
2. 필드명 변경시 IDE의 refactor 기능 연동 불가능

QueryDSL 방식은 1번은 해결할 수 있지만 2번은 해결 불가능하고, 모델 생성이라는 추가적인 작업이 필요해서 
exTree을 활용한방식이 좋아 보입니다.

**Comment by mhyeon-lee** [comment]
@seongahjo 해당 모듈의 README 에 명시하면 될거 같지만, 애매하다면 해당 모듈만 repo 를 따로 파는것도 방법일 수 있을거 같습니다.

아래처럼 lambda 안에서 마지막에 `Friend.getName()` 만 인식하고 앞에 `p.getFriend()` 는 인식 못할 줄 알았는데 해보니까 nested 구조로 다 파싱하는군요 (신기하네요)
`.set((Person p) -> p.getFriend().getName(), "john")`

![스크린샷 2021-10-02 오후 5 51 38](https://user-images.githubusercontent.com/5206572/135709826-c32e5996-1a90-4866-809c-c26d6598bae4.png)

---

QueryDSL 방식은 말씀하신대로 IDE 리팩터를 한번에 하지는 못하고 생성된 Expression 모델 의 리팩터를 별도로 해줘야 될거 같군요 (우선 빌드타임에 잡아주는것만으로도 크다고 생각되긴 합니다.)

---

ExTree 를 사용해서 Lambda 에 들어온 호출식을 Parsing 하고 저희가 사용하는 String 표현식에 맞게 변환시켜주는 작업을 해야 될거 같군요
우선 급한 이슈는 아니기에 천천히 탐구해볼만 할거 같습니다.

**Comment by seongahjo** [comment]
@mhyeon-lee 
넵 좋습니다. decompose와 전혀 관계 없는 표현식과 관련된 기능이라 마음이 편하네요.
