### ISSUE TITLE
Incompatibility between BuilderArbitraryCustomizer and manipulating the instance

### ISSUE THREAD

**Issue by njimenezotto** [naver/fixture-monkey#337]
I have a class with a BuilderArbitraryCustomizer where I set some Arbitraries.
In my tests, I want to use giveMeBuilder(MyClass).set(fieldName_managed_by_arbitrary, myValue).sample() to get an instance with my wished values. This is the arbitrary I use:

.use(Arbitraries.strings().numeric().ofMaxLength(3)).in(MyClass.MyClassBuilder::myField);

Expected
Instance with my entered value

Current result
Instance with random value from the arbitrary

**Comment by seongahjo** [comment]
@njimenezotto 
Hello. Could you give us an example for reproducing the problem?

**Comment by seongahjo** [comment]
close now. welcome to reopen!
