### ISSUE TITLE
Remove org.junit.platform.x dependencies

### ISSUE THREAD

**Issue by mhyeon-lee** [naver/fixture-monkey#35]
Remove `org.junit.platform.xx` dependencies.
Replace the utility code of `org.junit.platform.xx` to use internal code.

For example, removing the BeanArbitraryGenerator `ReflectionUtils` usage code and replace it with a utility code that does the same thing inside.

----

org.junit.platform.xx 의 유틸리티 사용한 코드들을 내부 코드를 사용하도록 대체합니다.
코드에서 org.junit.platform.xx 의존 코드들을 제거합니다.

예를 들어 BeanArbitraryGenerator 의 ReflectionUtils 사용 코드를 제거하고 동일한 동작을 하는 유틸리티 코드를 내부에 작성해서 대체합니다.

**Comment by seongahjo** [comment]
이 이슈는 org.junit.platform.xx 유틸리티 의존성을 제거하고 jqwik 의존성을 `api`에서 `implementation`으로 바꾸려는 의도이실까요?
