### ISSUE TITLE
Upgrade jqwik 1.6.0 version

### ISSUE THREAD

**Issue by mhyeon-lee** [naver/fixture-monkey#36]
- jqwik 1.6.0 version 으로 upgrade 합니다.
- jqwik 의 braking change 를 대응합니다.
- #34 #35 가 선행되어야 합니다.

**Comment by seongahjo** [comment]
아직 1.6.0이 안나온 것 같은데, Jqwik 1.6.0에서 이전에 제안하셨던 게 반영이 되는 걸까요?

**Comment by mhyeon-lee** [comment]
1.6.0-SNAPSHOT 으로 테스트해보고 있습니다.
테스트 해보고 우선 아래 PR 을렸는데, 아래 PR 만 반영되도 어느정도 해결될 것으로 보입니다.
(받아줄 지는 모르겠습니다.)
https://github.com/jlink/jqwik/pull/233

**Comment by seongahjo** [comment]
버전업이 완료됐으므로 close합니다.
