### ISSUE TITLE
Figure out why generating empty container in key

### ISSUE THREAD

**Issue by seongahjo** [naver/fixture-monkey#419]
https://github.com/naver/fixture-monkey/pull/418

`Map<Map<String, String>, String>>` 처럼 key 값이 컨테이너인 경우 생성할 때 반복적으로 size가 0인 경우가 발생한다.
size가 0이 되어 중복된 키가 발생하여 객체 생성에 실패하게 된다.
원인을 조사하고 정리한다.

**Comment by esfomeado** [comment]
I'm facing this issue as well. Any updates?

**Comment by seongahjo** [comment]
@esfomeado 
It had fixed since 0.4.3.

Are you using LabMonkey in 0.4.3?

**Comment by esfomeado** [comment]
@seongahjo Yes, I will create a replication.

**Comment by esfomeado** [comment]
@seongahjo You are right. It works with `Map<Map<String, String>, String>>` but if I use instead a more complex type it fails.

https://github.com/esfomeado/monkey-bug

`void testMapWithEnum()` - Fails

`void testMapWithString()` - Works fine
