### ISSUE TITLE
EnumMap isn't generated if the number of enum values is less than container min size

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#487]
If the container size is bigger then the number of enum values it will fail to generate the `EnumMap`.

This is a special case that should ignore the min container size.

Sample project:
https://github.com/esfomeado/monkey-enum-bug

Two tests are provided:

` void testWillAlwaysFail()` - It will fail always since the container size is bigger than the number of enum values.

`void testSometimesFail()` - It will only fail sometimes since sometimes the container size is the same as the number of enum values.

**Comment by seongahjo** [comment]
@esfomeado 
Thank you for reporting bug!

It would be fixed since 0.4.4
https://github.com/naver/fixture-monkey/pull/488

**Comment by esfomeado** [comment]
@seongahjo I've tested and it's working.

Thanks for the fix.
