### ISSUE TITLE
Display what field failed to generate

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#490]
It would be useful to know which field failed to generate instead of a generic message since sometimes isn't straightforward to see which field failed to generate and why.

**Comment by seongahjo** [comment]
Thank you for your suggestion.

We would add this feature before releasing 1.0.0!

If you have a good idea to deal with this issue, welcome to contribute!

**Comment by esfomeado** [comment]
I have to find some time to deep dive into the code.

**Comment by seongahjo** [comment]
@esfomeado 
Thank you for waiting.
It is implemented in `0.6.0`, please check it out!
