### ISSUE TITLE
Unmappable character for encoding Cp1252

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#500]
## Describe the bug
The compilation fails on a system that us Cp1252 encoding due to the Korean comments.

## Your environment
* Fixture Monkey: 0.4.5
* Java 17

## Steps to reproduce
Compile the code using Cp1252 encoding.

## Expected behaviour
Should compile successfully.

## Actual behaviour
Compilation fails.

Comments causing the issue:

`fixture-monkey\src\main\java\com\navercorp\fixturemonkey\arbitrary\ArbitraryTraverser.java:296`

`fixture-monkey\src\main\java\com\navercorp\fixturemonkey\arbitrary\DefaultContainerArbitraryNodeGenerator.java:141`

`fixture-monkey\src\main\java\com\navercorp\fixturemonkey\generator\ArrayBuilder.java:70`

**Comment by seongahjo** [comment]
@esfomeado 
We do not need comments because classes you mentioned are just for 0.3

Could you make a PR for removing comments you found?

I think it would be a meaningful action!

**Comment by esfomeado** [comment]
Sure I will take care of that.

I didn't do that in the first place since I didn't know if you wanted to keep the comments and I was unable to translate them.
