### ISSUE TITLE
Cannot set field

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#534]
## Describe the bug
When setting a field where the parent is an abstract class and the parent of the parent is also an abstract class it throws an error saying `No resolved property is found.`

## Your environment
Java 17

FixtureMonkey - 0.4.10

## Steps to reproduce
Run abstractTest().

https://github.com/esfomeado/fixture-monkey-bug/blob/master/src/test/java/com/example/bug/FixtureMonkeyTest.java

## Expected behaviour
Should set the field correctly.

## Actual behaviour
Throws error message saying `No resolved property is found.`

**Comment by seongahjo** [comment]
@esfomeado 
It would work when adding `Mark.class` in `interfaceImplements` options.
Just like below.

```java
.interfaceImplements(AbstractAuthor.class, List.of(Mark.class, John.class, Peter.class))
```

**Comment by esfomeado** [comment]
@seongahjo Thanks it solves that issue but I feel that it's weird and unintuitive having to put the class on the `interfaceImplements` to be able to set a field.

**Comment by esfomeado** [comment]
On my project adding the class to the `interfaceImplements` broken multiple tests.

They now complain about duplicates keys on the map.

I will try to replicate the issue and I will then update the tests.

**Comment by esfomeado** [comment]
Replication:

https://github.com/esfomeado/fixture-monkey-bug/blob/duplicated-keys/src/test/java/com/example/bug/FixtureMonkeyTest.java

**Comment by seongahjo** [comment]
@esfomeado 
>  I feel that it's weird and unintuitive having to put the class on the interfaceImplements to be able to set a field.

`interfaceImplements(AbstractAuthor.class, List.of(Mark.class, John.class, Peter.class))`
`interfaceImplements` is letting Fixture Monkey know what abstract class would be implemented not just for setting a field.
In this case `AbstractAuthor` could be one of `Mark`, `Jonh`, `Peter`.

I think you feel it is weird because setting a field is not a concern of `interfaceImplements`, is it right?

**Comment by esfomeado** [comment]
@seongahjo I assumed that the `interfaceImplements` was only used to let Fixture Monkey know what concrete classes to generate based on that interface/abstract class and not as well to know what concrete class could be set.

I guess the documentation needs a small note saying that this is the case.

And please check the bug that I mentioned of having duplicate values when you get a change.

I had to do a nasty workaround to make it work in the meantime.

Thanks for your support.

**Comment by seongahjo** [comment]
@esfomeado 
Could you try snapshot version?
`com.navercorp.fixturemonkey.snapshot:fixture-monkey:0.4.11-c5d6ec6`

**Comment by esfomeado** [comment]
@seongahjo It fixes the problem.

Thanks
