### ISSUE TITLE
Cannot invoke "net.jqwik.api.Arbitrary.asGeneric()" because "this.arbitrary" is null

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#535]
## Describe the bug
`Cannot invoke "net.jqwik.api.Arbitrary.asGeneric()" because "this.arbitrary" is null`

## Your environment
Java 17

FixtureMonkey - 0.4.10

## Steps to reproduce
Run abstractTest().

https://github.com/esfomeado/fixture-monkey-bug/blob/master/src/test/java/com/example/bug/FixtureMonkeyTest.java

## Expected behaviour
The test should pass.

## Actual behaviour
I get this exception:

`Cannot invoke "net.jqwik.api.Arbitrary.asGeneric()" because "this.arbitrary" is null`

**Comment by seongahjo** [comment]
@esfomeado 
It is fixed since 0.4.11~

**Comment by esfomeado** [comment]
Thank you, everything works flawlessly now.
