### ISSUE TITLE
Is there a way to create a Kotlin data class where all properties have non-nullable values?

### ISSUE THREAD

**Issue by doljae** [naver/fixture-monkey#551]
## Describe your question
Is there a way to create a Kotlin data class where all properties have non-nullable values?

For example...
```kotlin
data class A(
    val id:Long?,
    val name:String?,
    val inner: B?
)

data class B(
    val id:Long?,
    val name:String?,
    val inner: C?
)

data class C(
    val id:Long?,
    val name:String?,
)
```
When I have the class structure as above and create a fixture of class `A` with `LabMonkey`, I want to make all properties of class `A` non-nullable, and properties of its subclass(in this case, B & C) not only it's properties, but also itself too.

Is there any combination of settings that I can use in a situation like the one above?

FYI, the configuration below seems not work 😭 
```kotlin
val sut = LabMonkey.labMonkeyBuilder()
    .defaultNotNull(true)
    .plugin(KotlinPlugin())
    .build()
```

**Comment by seongahjo** [comment]
@doljae 
Hi~ 
`defaultNotNull` option only works for property has no a nullable marking.
A nullable marking refers to `@Nullable`, `?`

In this situation, you'd better to use `defaultNullInjectGenerator` option just like below.
```kotlin
val sut = LabMonkey.labMonkeyBuilder()
            .defaultNullInjectGenerator { NOT_NULL_INJECT }
            .plugin(KotlinPlugin())
            .build()
```

**Comment by doljae** [comment]
@seongahjo ,

Thanks for the detailed explanation 🙂 

In my case, using `defaultNullInjectGenerator` seems simpler. And if I need to create a complex fixture that includes nullable properties, I'll use `register` option.

Let me ask a question for clarity.

- Do the two `Labmonkey` settings you wrote as an example have the same effect? In other words, is it possible to create non-null fixtures regardless of property nullability for both properties and sub-properties of the fixture?

**Comment by seongahjo** [comment]
@doljae 
> Do the two LabMonkey settings you wrote as an example have the same effect?
In other words, is it possible to create non-null fixtures regardless of property nullability for both properties and sub-properties of the fixture?

Yes, two examples generate not-null property regardless of property nullability.

> Can you explain a bit more about the effect of the defaultNotNull option?

As you know, a Java property could be null even if there is no `@Nullable` marking.
If `defaultNotNull` is true, a Java property without `@Nullable` would not be null.
But a Java property with `@Nullable` might be null even if `defaultNotNull` is true. 
If `defaultNotNull` is false, a Java property might be null.

But in Kotlin, a property could not be null.
A property with `?` means it might be nullable same as property with `@Nullable` in Java.
So `defaultNotNull` option does not work in Kotlin.

We think that a nullable property should not always be null.
But in a special case, it could be not null.
In that case it should be exposed in a test case by `setNotNull`

**Comment by doljae** [comment]
@seongahjo 
I understand.

Fixture Monkey supports so many functions and settings, but I'm not familiar with it yet 😓 
Thank you for the detailed explanation 🙇
