### ISSUE TITLE
Need fixture monkey Intellij plugin update.

### ISSUE THREAD

**Issue by donemin** [naver/fixture-monkey#566]
## Describe the feature you request
https://plugins.jetbrains.com/plugin/19589-fixture-monkey-helper/versions

I cannot install this plugin cause of not supported IDEA version.
currently latest Intellij IDEA version is 2022.3.2.

Plugin only supports these version of IDEA.
`IntelliJ IDEA Ultimate — 2021.3 — 2022.2.4`

Need to update this plugin for latest Intellij IDEA.

**Comment by seongahjo** [comment]
@donemin 
It may be fixed in next week.
I would notice you when new version plugin is released.

**Comment by donemin** [comment]
@seongahjo 
checked. It works!
