### ISSUE TITLE
class java.lang.Class cannot be cast to class java.lang.reflect.TypeVariable

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#570]
## Describe the bug
When generating a class using fixture monkey 0.4.12 or newer I get this error:

```
class java.lang.Class cannot be cast to class java.lang.reflect.TypeVariable (java.lang.Class and java.lang.reflect.TypeVariable are in module java.base of loader 'bootstrap')
```

It works fine on fixture monkey 0.4.11.

## Your environment
0.4.12+
Java 17

## Steps to reproduce
Run the `entityTest()` located in this repo:
https://github.com/esfomeado/fixture-monkey-bug/blob/master/src/test/java/com/example/bug/FixtureMonkeyTest.java

## Expected behaviour
Should generate the class

## Actual behaviour
Throws error

**Comment by seongahjo** [comment]
@esfomeado 
Thank you for reporting an issue.
It'll be fixed in 0.4.14!

Is it the issue you mentioned in this PR?
https://github.com/naver/fixture-monkey/pull/519#issuecomment-1426297663

**Comment by seongahjo** [comment]
@esfomeado 
`0.4.14` is released!

**Comment by esfomeado** [comment]
I found others. I will report them later
