### ISSUE TITLE
Is it possible to exclude certain Enum values?

### ISSUE THREAD

**Issue by armandino** [naver/fixture-monkey#572]
## Describe your question

I would like to create an object that has an enum field, for example `enum OrderStatus { SUBMITTED, SHIPPED, DELIVERED, CANCELLED, ... }`.

Is it possible to create an `Order` but exclude some statuses? For example:

```java
LabMonkey sut = LabMonkey.labMonkeyBuilder()
      .objectIntrospector(BeanArbitraryIntrospector.INSTANCE)
      .defaultNotNull(true)
      .build();

Order order = sut.giveMeBuilder(Order.class)
      .set("status", <any status except SHIPPED and CANCELLED>)
      .sample();
```

**Comment by seongahjo** [comment]
@armandino 
You could use `set` or `setPostCondition` either.
You should be careful when using `setPostCondition`, since it may causes a performance issue if not using correctly.


### set

```java
Order order = sut.giveMeBuilder(Order.class)
      .set("status", Arbitraries.of(OrderStatus).filter(it -> it != SHIPPED || it != CANCELLED))
      .sample();
```

### setPostCondition

```java
Order order = sut.giveMeBuilder(Order.class)
      .setPostCondition("status", OrderStatus.class, it -> it != SHIPPED || it != CANCELLED)
      .sample();
```

**Comment by armandino** [comment]
@seongahjo perfect, thank you! The first solution seems like exactly what I need. Can I ask what's the difference between `set` and `setPostCondition`?

**Comment by seongahjo** [comment]
@armandino 
The main difference is **scope**.

In `set`, filtering only affects when creating an enum value, not whole `Order`

In `setPostCondition`, filtering affects creating `Order`. 
If there are many filtering in creating `Order`, it may have a performance issue.

**Comment by armandino** [comment]
@seongahjo, I see. Thank you for your help! I'll close the issue.
