### ISSUE TITLE
Allow to specify how interfaces/abstract classes are resolved

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#582]
## Describe the feature you request
Right now we have to specify the subtypes of an interface using `interfaceImplements`.

This works fine when you just have a small number of interfaces/abstract classes but in a large project it gets harder to maintain.

To solve this problem I would like to be able to provide a way to tell `FixtureMonkey` how to get the subtypes for that interface. For instance an "Interface Resolver" that would be called to get the subtypes of an Interface.

By default this "Interface Resolver" would check the `interfaceImplements` defined to keep the behaviour the same.

**Comment by seongahjo** [comment]
@esfomeado 
As I understand it, you need a new option to determine the implementation of the interface dynamically.
In order to define an interface, we need to know which implementations are actually available.
I think there are two ways.

1. Specify the package in which the implementation exists
2. Specify the implementations just like `interfaceImplements`

Any other ideas?

**Comment by esfomeado** [comment]
Yes, correct.

How would option 1 work if for instance there are multiple classes on that package that are not implementations of the interface? Will it handle sub packages as well?

My initial plan was to use reflection to get all the available implementations for the interface.

**Comment by seongahjo** [comment]
@esfomeado 
How about making custom `ObjectPropertyGenerator` or using existing `ObjectPropertyGenerator`?

https://github.com/naver/fixture-monkey/blob/4d9dfb5e1680db3b1ac8f4a8a46f4a434e7889bc/fixture-monkey-api/src/main/java/com/navercorp/fixturemonkey/api/generator/InterfaceObjectPropertyGenerator.java#L38-L38

If you use reflection to get all the available implementations and then make your own `InterfaceObjectPropertyGenerator`.

You could use `pushAssignableTypeObjectPropertyGenerator` option.

```java
pushObjectPropertyGenerator(
    new MatherOperator<>(
        p -> Modifier.isAbstract(Types.getActualType(p.getType()).getModifiers()), 
        new CustomObjectPropertyGenerator()
    )
);
```

In this case, You could use third-party library. https://github.com/ronmamo/reflections/

**Comment by esfomeado** [comment]
@seongahjo Thanks. That's literally what I wanted.

Works like a charm
