### ISSUE TITLE
class 내 동일한 class 타입 필드 생성 시, stackOverFlowError 발생 문의 

### ISSUE THREAD

**Issue by Min-Jae-Kim** [naver/fixture-monkey#587]
## Describe the bug
안녕하세요. 
class 내 동일한 class 타입 필드 생성 시, stackOverFlowError가 발생합니다. 

## Your environment
* version of Fixture Monkey : 0.3.1
* version of Java/Kotlin : 1.8 

## Steps to reproduce
아래와 같이 자기 자신과 동일한 타입의 필드를 갖는 class를 정의 후, FixtureMonkey로 객체를 생성합니다. 

```java
//Foo.class
@Getter
@Setter
public class Foo {
	private String text;
	private Foo anotherFoo;
}
```
```java
//FixtureMonkey를 활용한 Foo 객체 생성
class FooTest {

	private static FixtureMonkey FIXTURE = FixtureMonkey.create();

	@Test
	public void test() {
		Foo foo = FIXTURE.giveMeOne(Foo.class);
	}

	@Test
	public void test2() {
		Foo foo = FIXTURE.giveMeBuilder(Foo.class).setNull("anotherFoo").sample(); // anotherFoo에 대해서도 동일한 에러 발생
	}
}
```

## Expected behaviour
아무래도 stackOverFlowError 가 발생하는 이유는 
재귀적으로 계속 참조하여 무한정 생성하여 발생하는 것으로 보입니다. 

이를 우회하기 위해 
자기 자신의 타입에 대하여 값을 생성할 때, 제한을 두도록 하거나 
아니면 생성 시, 해당 필드는 생성을 못하도록 하는 방법이 있을지 문의드립니다. 

## Actual behaviour
stackOverFlowError가 발생하빈다. 
![image](https://user-images.githubusercontent.com/16396892/222658700-e1156af3-562f-4036-9ec5-0493b21fe99f.png)

**Comment by seongahjo** [comment]
@Min-Jae-Kim 
문제가 발생한 버전을 명시해주실 수 있을까요?
0.4.9부터 자기 자신을 필드로 가질 경우 생성을 지원하고 있습니다.
https://github.com/naver/fixture-monkey/blob/4d9dfb5e1680db3b1ac8f4a8a46f4a434e7889bc/fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyTest.java#L1569-L1569

0.4 버전을 사용하고 계신다면 Fixture Monkey 인스턴스가 아닌 LabMonkey 인스턴스를 사용하시는 걸 권장드립니다.
큰 이슈가 없으시다면 0.5로 올리시는 것도 추천드립니다.

**Comment by Min-Jae-Kim** [comment]
@seongahjo 님
저희 팀에서는 `0.3.1` 버전을 사용하고 있는데요.
말씀 주신대로 `0.4.9` 버전 이상으로 올려서 사용했는데도 동일한 이슈가 발생했습니다. 
(0.4.14 버전을 적용했습니다.)

공유주신 테스트 코드와 같이 동일하게 진행하였습니다. 

```java
class SelfRecursiveObjectTest {

	@Property
	void sampleSelfRecursiveObject() {
		FixtureMonkey sut = FixtureMonkey.builder()
			.defaultNotNull(true)
			.build();

		SelfRecursiveObject actual = sut.giveMeOne(SelfRecursiveObject.class);

		assertNotNull(actual.getRecursive());
	}
}
```

![image](https://user-images.githubusercontent.com/16396892/222671612-2877d8bd-2052-421a-ade7-6af4f632e9bb.png)

0.5로 올리니 이슈는 발생하지 않습니다.

**Comment by seongahjo** [comment]
@Min-Jae-Kim 
넵, 0.5를 사용하시는 데 이슈 없으시면 0.5를 사용하시면 될 것 같습니다.

혹시라도 0.4를 사용하시고 싶으시면 다음과 같이 사용하시면 됩니당.

```
class SelfRecursiveObjectTest {

	@Property
	void sampleSelfRecursiveObject() {
		LabMonkey sut = FixtureMonkey.labMonkeyBuilder()
			.defaultNotNull(true)
			.build();

		SelfRecursiveObject actual = sut.giveMeOne(SelfRecursiveObject.class);

		assertNotNull(actual.getRecursive());
	}
}
```

**Comment by Min-Jae-Kim** [comment]
@seongahjo 님
`0.5.0` 으로 버전업 이슈 해결하였습니다. 

버전 업 이후, 별도 확인이 필요하다면
이슈 올리도록 하겠습니다. 

해당이슈는 close 하겠습니다. 
감사합니다.
