### ISSUE TITLE
Cannot generate Class<?>

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#609]
## Describe the bug
If an object contains a field of type `Class<?` fixture monkey fails to generate it.

## Your environment
* 0.5.2
* Java 17

## Steps to reproduce
https://github.com/esfomeado/fixture-monkey-bug/blob/ad6ccbd7c841501c42ce8dc0edaaeb1be1328110/src/test/java/com/example/bug/FixtureMonkeyTest.java#L31

## Expected behaviour
To be honest I'm not sure either. I guess ideally it would use a random class or a hardcoded class like `String` for instance or in last case set the value to null.

## Actual behaviour
Error is thrown.

```
java.lang.Class.<init>()
java.lang.NoSuchMethodException: java.lang.Class.<init>()
```

**Comment by seongahjo** [comment]
@esfomeado 
Sorry for the late response. I'm not sure too. I think it is up to the client.
I think you should better use an option `pushAssignableTypeArbitraryIntrospector` to choose the value to return just like below.

```java
.pushAssignableTypeArbitraryIntrospector(
			Class.class,
			context -> new ArbitraryIntrospectorResult(Arbitraries.just(null))
		)
```

**Comment by esfomeado** [comment]
That´s what I end up doing.

Thanks
