### ISSUE TITLE
Fluent arbitrary builder group

### ISSUE THREAD

**Issue by chanhyeong** [naver/fixture-monkey#628]
## Describe the feature you request

`Class<?>`s are passed to `registerGroup`, which is hard to understand what value should be passed when I just read the code.
I think it would be better to provide a more explicit interface then interface.

현재 `registerGroup` 으로 넘기는 값은 `Class<?>` 들로, 코드만으로는 어떤 값을 넘겨야하는지 바로 파악이 어렵다고 생각합니다
reflection 을 통한 방법 외에 조금 더 명시적인 인터페이스를 제공하는게 어떨지 싶습니다

## (Optional): Suggest A Solution

- declare `ArbitraryBuilderGroup`
```java
public interface ArbitraryBuilderGroup {
    default List<ArbitraryBuilder> getArbitraryBuilders() {
        return creator.getArbitraryBuilders();
    }

    ArbitraryBuilderCreator addBuilders(ArbitraryBuilderCreator creator);
}
```

- declare `ArbitraryBuilderCreator` (a builder of ArbitraryBuilders)
- implement `ArbitraryBuilderGroup`
```java
public class OrderBuilderGroup implements ArbitraryBuilderGroup {

    @Override
    public ArbitraryBuilderCreator addBuilders(ArbitraryBuilderCreator creator) {
        return creator.of(A.class)
            .builder(it -> // UnaryOperator<ArbitraryBuilder<A>>
                it.set("*", "")
                ...
            )
            .of(B.class)
            .builder(it -> // UnaryOperator<ArbitraryBuilder<B>>
                it.set("name", Arbitraries.strings())
                ...
            )
    }
}
```

- registerBuilderGroup (a similar way to Jackson `registerModules`)
```java
FixtureMonkey.builder()
    .registerGroup(
        new OrderBuilderGroup(),
        new PaymentBuilderGroup(),
        ...
    )
```

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by seongahjo** [comment]
넵 제안해주신대로 명시적인 인터페이스가 있으면 사용하기 더 편할 것 같아 좋은 것 같습니다.
다만 다음과 같은 사항을 추가적으로 고려해야할 것 같습니다.

1. ArbitraryBuilderCreator에서 일반적인 `Class<?>` 형태의 타입이 아닌 TypeReference를 지원할 수 있을지
2. ArbitraryBuilderCreator에서 ArbitraryBuilder를 어떻게 생성할지
  * FixtureMonkey 인스턴스에 위임하여 생성하는 방식일지
  * FixtureMonkey 인터페이스를 새로 구현하여 생성할지

**Comment by chanhyeong** [comment]
개인적으로 구현해보던게 있는데 `Class<?>`, `TypeReference<?>`, value 까지 지원이 가능했습니다

https://github.com/naver/fixture-monkey/blob/8f90a30630c4fd31b5a41166075f0efc2ebe9422/fixture-monkey/src/main/java/com/navercorp/fixturemonkey/FixtureMonkeyBuilder.java#L369

기존에 구현해주신 registerGroup 에서 하던 방식을 참고했는데
`Function<FixtureMonkey, ? extends ArbitraryBuilder<?>> registerArbitraryBuilder` 와 같은 방식으로 해봤습니다

괜찮으시면 조금 더 다음어서 draft 로 올려보겠습니다
