### ISSUE TITLE
InnerSpec test fails from JDK16

### ISSUE THREAD

**Issue by SooKim1110** [naver/fixture-monkey#633]
## Describe the bug
Map setting fails in `InnerSpecTest` from JDK16.
(Test only fails when it is made in the `fixture-monkey` module.)

## Your environment
* version of Fixture Monkey
0.5.5
* version of Java/Kotlin
From 16

## Steps to reproduce
Run `InnerSpecTest` after changing the JDK version.

## Expected behaviour
`InnerSpecTest` should success.

## Actual behaviour
`InnerSpecTest` fails.

**Comment by seongahjo** [comment]
It will be fixed in 0.6.9.
https://github.com/naver/fixture-monkey/pull/752
