### ISSUE TITLE
Map genericsTypes must be have 2 generics type for key and value

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#648]
## Describe the bug
When mapping a FilePart I get the following error:

`Map genericsTypes must be have 2 generics type for key and value`.

The workaround is to set the field to `null` but I would except fixture-monkey to do this for me. 

## Your environment
* 0.5.6
* Java 17

## Steps to reproduce
https://github.com/esfomeado/fixture-monkey-bug/blob/master/src/test/java/com/example/bug/FixtureMonkeyTest.java#LL39C14-L39C14

## Expected behaviour
It is unable to set the value of the field should set it to null

## Actual behaviour
Exception is thrown.

**Comment by seongahjo** [comment]
@esfomeado 
It is fixed in 0.5.7.
Thank you for making an issue!
