### ISSUE TITLE
Is there a way for the DefaultNullInjectGenerator to identify annotations with a CLASS retention policy?

### ISSUE THREAD

**Issue by jbl428** [naver/fixture-monkey#653]
## Describe your question

There is some class.

```java
import org.jetbrains.annotations.NotNull;

class User {
  @NotNull
   private String name
}
```

I believe that the `NotNull` annotation on the `name` property implies that it should always have a non-null value when generated by the builder. But it was't

I have found that `DefaultNullInjectGenerator` can not find `name` is `NotNull` because retention policy of `org.jetbrains.annotations.NotNull` is `CLASS`.

`DefaultNullInjectGenerator` have some annotation list. some of them have `CLASS` retention policy.

```java
public static final List<String> DEFAULT_NULLABLE_ANNOTATION_TYPES = Collections.unmodifiableList(
  Arrays.asList(
	  "javax.annotation.Nullable",
	  "org.springframework.lang.Nullable",
	  "edu.umd.cs.findbugs.annotations.Nullable",
	  "org.jetbrains.annotations.Nullable",
	  "com.sun.istack.internal.Nullable",
	  "androidx.annotation.Nullable",
	  "android.support.annotation.Nullable",
	  "org.checkerframework.checker.nullness.qual.Nullable",
	  "org.eclipse.jdt.annotation.Nullable",
	  "org.eclipse.jgit.annotations.Nullable",
	  "org.jmlspecs.annotation.Nullable"
  )
);
```

If there is no way  to identify these annotations, I suggest considering the removal of each annotation to prevent any misunderstandings.

**Comment by seongahjo** [comment]
@jbl428 
Hello, I think you'd better to use `pushNullInjectGenerator` option.

You could use this option as below.

```java
.pushNullInjectGenerator(
	new MatcherOperator<>(
		property -> property.getAnnotation(NotNull.class).isPresent(),
		context -> NOT_NULL_INJECT
	)
)
```

It would be worked for all properties have `@NotNull`.
If you have any more questions, please feel free to ask.

**Comment by jbl428** [comment]
I have tried your solution. but i think it does not work.

sample code repo: [null-inject-test branch](https://github.com/jbl428/fixture-monkey/blob/null-inject-test/fixture-monkey/src/test/java/com/navercorp/fixturemonkey/test/FixtureMonkeyBuilderTest.java)

```java
FixtureMonkeyTestSpecs.JetBrainAnnotationObject jetBrainAnnotationObject = FixtureMonkey.builder()
	.objectIntrospector(ConstructorPropertiesArbitraryIntrospector.INSTANCE)
	.pushNullInjectGenerator(
		new MatcherOperator<>(
			property -> {
				boolean present = property.getAnnotation(NotNull.class).isPresent();
				return present;
			},
			context -> NOT_NULL_INJECT
		)
	)
	.build()
	.giveMeOne(FixtureMonkeyTestSpecs.JetBrainAnnotationObject.class);
```

If i check the result of `property.getAnnotation(NotNull.class).isPresent();` it is always `false`.
`property` does not have jetbrain `@NotNull` annotation in `annotationMap`.

![CleanShot 2023-05-27 at 09 31 01@2x](https://github.com/naver/fixture-monkey/assets/22140938/9377bbe9-64e5-4268-a4ec-190aceabf831)

**Comment by seongahjo** [comment]
@jbl428 
As I know, `@org.jetbrains.annotations.NotNull` is an annotation for IntelliJ IDEA's static analysis, not for validation.
Due to its purpose, It could not be captured in runtime.

I think It is better to use [Bean Validation annotations](https://beanvalidation.org/).
Are there any reasons for using `@org.jetbrains.annotations.NotNull` instead of Bean Validation annotations?

**Comment by jbl428** [comment]
@seongahjo 
My project is written in Java for the entity classes and uses kotiln for the business logic.
To take advantage of kotiln's null safety, each entity's properties must be annotated to satisfy JSR305 (like `@org.jetbrains.annotations.NotNull`)

I found that `org.springframework.lang.NonNull` is another jsr305 compliant annotation and the retention policy is `RUNTIME`, so I could use this annotation.

My suggestion is to remove annotations whose retention policy is `CLASS` in `DefaultNullInjectGenerator`.
What do you think?

**Comment by seongahjo** [comment]
@jbl428 
Yes, it sounds great.
If you don't mind, could you make a PR for removing annotations whose retention policy is `CLASS` in `DefaultNullInjectGenerator`?
It would be very helpful.
