### ISSUE TITLE
support @Digits in JavaxValidationPlugin and JakartaValidationPlugin

### ISSUE THREAD

**Issue by seongahjo** [naver/fixture-monkey#664]
## Describe the feature
Improves supporting `@Digits` in `JavaxValidationPlugin` and `JakartaValidationPlugin`

## Objective
* supports `@Digits` annotation property `fraction`
* supports `@Digits` annotation property `integer`

### fraction
An object generated by `FixtureMonkey` should satisfy given fraction.
It is not supported now.

### integer
`JavaxValidationIntegerConstraint` or `JakartaValidationIntegerConstraint` generated by `@Digits` should be more precisely.

```java
@Value
public class TestSpec {
    @Digits(integer = 2)
    private int digitsValue;
}
```
For example, digitsValue should be between `-99 ~ -10`, `10 ~ 99`.
But `JavaxValidationIntegerConstraint` or `JakartaValidationIntegerConstraint` created now represents `-99~99`.

**Comment by coderr01** [comment]
@seongahjo i want to contribute to the issue. Can you elaborate for better understanding ?

**Comment by seongahjo** [comment]
@coderr01 
Hello, thank you for your interest in this issue.
I have updated the issue.
Please check it out, and let me know if you need any more information.
