### ISSUE TITLE
Set field for builder that have customizer not work

### ISSUE THREAD

**Issue by phuc16102001** [naver/fixture-monkey#668]
## Describe the bug

I want to create an object from a class which have Builder annotation. However, the class that contains a field which is not Builder (from a library). So the `BuilderArbitraryIntrospector` will not work. As a result, I have customized that field to be excluded and set in the `giveMeBuilder`, but it still give null.

Here is the example, the class A is builder, which contains class B not Builder.

```java
@Builder
class A {
    private String someField;
    private B fieldB;
}

// This is from the library (not Builder)
@AllArgsConstructor
class B {
   private String fieldC;
}

public class ACustomizer implements FixtureCustomizer<A> {
    @Override
    public void customizeProperties(ChildArbitraryContext childArbitraryContext) {
        childArbitraryContext.removeArbitrary(property -> "fieldB".equals(property.getName()));
    }

    @Nullable
    @Override
    public A customizeFixture(@Nullable A object) {
        return object;
    }
}

private final FixtureMonkey fixtureMonkey = FixtureMonkey.builder()
    .pushAssignableTypeFixtureCustomizer(A.class, new ACustomizer())
    .objectIntrospector(BuilderArbitraryIntrospector.INSTANCE)
    .defaultNotNull(true)
    .build();

@Test
void testCode() {
    B fieldB = new B("123");
    A createdObject = fixtureMonkey.giveMeBuilder(A.class)
	.set("fieldB", fieldB).sample();
    Assertions.assertNotNull(createdObject.getFieldB());
}
```

## Your environment
Fixture monkey version: 0.5
Java version: 
- JDK17
- Gradle 8.1
- Spring 3.1

## Steps to reproduce
Mentioned in the description

## Expected behaviour
The fieldB should not be null.

## Actual behaviour
The field B is null.

Thank you 🙇

**Comment by seongahjo** [comment]
@phuc16102001 
Hello, `removeArbitray` is not recommended in this situation.
`removeArbitrary` means remove the property `fieldB`, so `set` does not work as well.

In this situation, you'd better use `pushExactTypeArbitraryIntrospector` .
You have to find out which introspector would generate `B`.
B has `@AllArgsConstructor`, so `ConstructorPropertiesArbitraryIntrospector` would work if you have `lombok.anyConstructor.addConstructorProperties=true` in your `lombok.config`

```java
private final FixtureMonkey fixtureMonkey = FixtureMonkey.builder()
    .objectIntrospector(BuilderArbitraryIntrospector.INSTANCE)
    .pushExactTypeArbitraryIntrospector(B.class, ConstructorPropertiesArbitraryIntrospector.INSTANCE)
    .defaultNotNull(true)
    .build();
```

If not work, please let me know. 
Thank you

**Comment by phuc16102001** [comment]
But what if the B class does not have the @AllArgsConstructor too? Particularly, it is the [GeoBoundingBox](https://github.com/elastic/elasticsearch/blob/641e331a9e7e721af5c18610a009d3f2edf9321e/server/src/main/java/org/elasticsearch/common/geo/GeoBoundingBox.java#L23) in Elastic Search. I have tried the `ConstructorPropertiesArbitraryIntrospector` but it throw this:

```java
Primary Constructor does not exist. type GeoBoundingBox
java.lang.IllegalArgumentException: Primary Constructor does not exist. type GeoBoundingBox
```

**Comment by seongahjo** [comment]
@phuc16102001 
In this case you could setup just as below.

```java
private final FixtureMonkey fixtureMonkey = FixtureMonkey.builder()
    .objectIntrospector(BuilderArbitraryIntrospector.INSTANCE)
    .pushExactTypeArbitraryIntrospector(B.class, (ctx) -> new ArbitraryIntrospectorResult(Arbitraries.just(null)))
    .defaultNotNull(true)
    .build();

@Test
void testCode() {
    B fieldB = new B("123");
    A createdObject = fixtureMonkey.giveMeBuilder(A.class)
	.setJust("fieldB", Values.just(fieldB)).sample();
    Assertions.assertNotNull(createdObject.getFieldB());
}
```

**Comment by phuc16102001** [comment]
Which version of Fixture Monkey are you using? Because I cannot find the `setJust` method.

**Comment by seongahjo** [comment]
@phuc16102001 
Oh, sorry, you would use `set` instead of `setJust`

**Comment by phuc16102001** [comment]
Oh thank you, it works now. 🎉 

Ah also where I can find the latest document for the Fixture Monkey? Currently, it the 0.5.6 version has already available right? But the document still 0.5.0 which has some deprecated methods.

**Comment by seongahjo** [comment]
@phuc16102001 

> the 0.5.6 version has already available right?
Yes, 0.5.7 is the latest version.

> where I can find the latest document for the Fixture Monkey

You'd better to check [release](https://github.com/naver/fixture-monkey/releases) 
Document is now out-of-date since updating documentation has a lower priority.
I'll update the document as soon as possible.

**Comment by phuc16102001** [comment]
Ok thank you very much.
I will close the issue then.
Once again, thank you! 🙇
