### ISSUE TITLE
support generating lambda type

### ISSUE THREAD

**Issue by seongahjo** [naver/fixture-monkey#678]
## Objective
support generating lambda type.

### Java
* Supplier<T>
* Function<T, U>

### Kotlin
* [Function](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-function.html)

### Requirements
1. could be set lambda itself, for example `set("supplier", (Supplier<String>) () -> "test")`

**Comment by mollder** [comment]
Hi, I'm interested in this open source, and if this issue is not reflected yet, is it okay for me to try to solve this issue?

**Comment by seongahjo** [comment]
@mollder 
Hello, sure. Thank you for your interest. 
If you have any questions, please do not hesitate to ask.

I think it is good approach to take a look at the implementations of`ArbitraryIntrospector` and `PropertyGenerator`

**Comment by mollder** [comment]
Thank you for the explanation.

I'll look at the Arbitrary Introspector and Property Generator that you mentioned, and then I'll aim to raise the pr in about two weeks
