### ISSUE TITLE
Random a list of element that has a unique field

### ISSUE THREAD

**Issue by phuc16102001** [naver/fixture-monkey#699]
## Describe your question

Hi guys, I am finding for a solution that can generate a list of object, whose field are unique.
For example, I have a class `ClassA` has `fieldX`. How can I generate a list of `ClassA` by all the `fieldX` of generated objects are unique?

```java
class ClassA { private String fieldX; }

private final FixtureMonkey fixtureMonkey = FixtureMonkey.builder().defaultNotNull(true).build();
List<ClassA> listA = fixtureMonkey.sampleList(nSample);

for (ClassA obj1: listA) {
   for (ClassA obj2: listA) {
       if (!obj1.equals(obj2)) {
           assertNotEqual(obj1.fieldX, obj2.fieldX);
       }
   }
}
```

Thank you~

## What I have try
I have checked the unique random list of jqwik as the document said, but it not suitable to the thing I want:
- [Fixture monkey - Arbitrary](https://naver.github.io/fixture-monkey/docs/v0.5/components/arbitrary/)
- [JQWIK - Unique element](https://jqwik.net/docs/current/user-guide.html#unique-elements)

**Comment by phuc16102001** [comment]
Currently, I am using this solution:

```
List<ClassA> listA = fixtureMonkey.setLazy("fieldX", (Supplier<String>)() -> UUID.randomUUID().toString()))sampleList(nSample);
```

Do you guys have any better solution? 
With the above solution, I cannot globally config the `FixtureMonkey` object.

**Comment by phuc16102001** [comment]
I have resolved the problem as follow:

```java
private final FixtureMonkey fixtureMonkey = FixtureMonkey.builder().defaultNotNull(true)
     .pushArbitraryIntrospector(new MatcherOperator<>(
            (property) -> ("fieldX".equals(property.getName())),
	    (ctx) -> new ArbitraryIntrospectorResult(Arbitraries.create(() -> UUID.randomUUID().toString()))))
     .build();
```

So I will close this issue, if you have any better solution, please notify me.
Thank you~

**Comment by seongahjo** [comment]
I think the solution has a dependency with specific type.
I'll provide a better solution for making a unique value in `0.6.1`.

**Comment by phuc16102001** [comment]
> I think the solution has a dependency with specific type. (ex, UUID)

The data type of `fieldX` is String, I just want to random a unique string so I used the UUID.

> I'll provide a better solution for making a unique value in 0.6.1.

Thank you!
