### ISSUE TITLE
Repeated chars

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#708]
## Describe the bug
I has facing some random test failure and after further investigation I found the following issue.
In my application I have a field that needs to be unique but fixture monkey is generating a duplicate value in some occasions. I gave a big range from the minimum string length to the max string length so the chances of this happening should be close to 0 but it´s not the case.

One thing that I noticed is that this duplicated values are always the a string with the same characters e.g. "AAAAAA". So I tried to set `repeatedCharts` to 0 but made no difference at all. I would expect with the value set to 0 for no duplicated characters to occur.

Not sure why but Fixture Monkey generates with more frequency than it should this kind of strings with all characters being equal.

## Your environment
Java 17
Fixture Monkey 0.6.1

## Steps to reproduce
https://github.com/esfomeado/fixture-monkey-bug/blob/master/src/test/java/com/example/bug/FixtureMonkeyTest.java

## Expected behaviour
Shouldn´t generated values with repeated chars

## Actual behaviour
Generates values with repeated chars

**Comment by seongahjo** [comment]
@esfomeado 
`Arbitrary` does not work as we expect.

The test below fail as well.
```java
@Property
	void arbitraryRepeatChar() {
		StringArbitrary strings = Arbitraries.strings().repeatChars(0);
		Set<String> set = new HashSet<>();
		
		for (int i = 0; i < 100; i++) {
			set.add(strings.sample());
		}

		then(set).hasSize(100);
	}
```

We'll add a new feature to make a unique value in `0.6.2`.

**Comment by jyaquinas** [comment]
has this issue been addressed? 
I'm facing a similar issue.
Even if i set 
```java
.set("someLongField", Arbitraries.longs().injectDuplicates(0))
``` 
it will generate duplicate values from time to time.

**Comment by seongahjo** [comment]
@jyaquinas 
Hello, if you are using version above 1.0.24. You can use as below.

```java
LongArbitrary sharedLongArbitrary = Arbitraries.longs(); // it should be shared within your unique scope.

.set("$[*]", Values.unique(() -> globalLongArbitrary.sample()))
```

Thank you.

**Comment by jyaquinas** [comment]
Thanks! Would be great to see this in the docs. Maybe I couldn't find it.
