### ISSUE TITLE
Value not being set

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#733]
## Describe the bug
On my example the `version` value is not being set. Instead the default value is used.

## Your environment
* Fixture Monkey: 0.6.3
* Java 17

## Steps to reproduce
https://github.com/esfomeado/fixture-monkey-bug/blob/master/src/test/java/com/example/bug/FixtureMonkeyTest.java#L68

## Expected behaviour
Should set the value

## Actual behaviour
Does not set the value

**Comment by seongahjo** [comment]
@esfomeado 
It is fixed in `0.6.4`. Please check it out!

**Comment by esfomeado** [comment]
It works thanks
