### ISSUE TITLE
The string type data of objects created with fixtureMonkey in kotlin is strange.

### ISSUE THREAD

**Issue by KJongHyun** [naver/fixture-monkey#739]
## The string type data of objects created with fixtureMonkey in kotlin is strange.
**gradle 세팅**
![image](https://github.com/naver/fixture-monkey/assets/18495291/60c11baa-e61e-40b2-a85a-8cd6aa6536eb)

**테스트 세팅**
![image](https://github.com/naver/fixture-monkey/assets/18495291/59b6f060-e075-467d-a0b5-b2a930b83618)

**출력 내용**
![image](https://github.com/naver/fixture-monkey/assets/18495291/973b217b-aeb7-4289-82fd-b7c800e264b3)

**데이터 구조**
![image](https://github.com/naver/fixture-monkey/assets/18495291/1fb6f3a9-67d5-4342-a0e2-c944a9538ffb)

String 타입으로 선언된 프로퍼티의 임의 데이터가 인코딩 문제가 있는것 처럼 출력 됩니다.
세팅의 문제인지 의도된 기능인지 궁금합니다.
조금 더 readable한 임의 데이터로 생성하는게 가능할지 문의드립니다

**Comment by seongahjo** [comment]
@KJongHyun 
안녕하세요.
넵, 기본적으로 생성하는 `String` 타입은 `출력 내용`에서 확인하신 것처럼 의도적으로 생성하고 있습니다.
`String`에서 유효하지 않은 문자열 (control block) 등이 입력될 수 있는 환경을 테스트하기 위한 목적입니다.

사용하시는 환경에서 불필요하다면 변경할 수 있습니다. 만약 알파벳만 생성하시고 싶으시다면 다음과 같이 설정 가능합니다.

```kotlin
FixtureMonkey.builder()
            .javaTypeArbitraryGenerator(object :JavaTypeArbitraryGenerator{
                override fun strings(): StringArbitrary = Arbitraries.strings().alpha()
            })
            .build()
```

조금 더 readable한 데이터를 원하신다면 dataFaker 라이브러리를 활용하는 방법도 있는데요. 필요하시면 말씀해주시면 공유해드리겠습니다.

**Comment by KJongHyun** [comment]
@seongahjo 안녕하세요.
먼저 답변감사합니다!
답변 주신 내용으로도 충분하지만, DataFaker에 대한 내용도 공유해주시면 감사히 참고하겠습니다:)

**Comment by seongahjo** [comment]
@KJongHyun 
[DataFaker](https://github.com/datafaker-net/datafaker/)는 fake data를 만들어주는 라이브러리인데요, 이걸 픽스쳐 몽키에 적용해서 사용하면 그럴싸한 데이터를 만들수 있습니다.

픽스쳐 몽키의 `pushArbitraryIntrospector` 옵션을 사용하면 적용 가능한데요, 기존에 String에 설정하셨던 다른 옵션들이 무시되므로 주의해서 사용해야 합니다. ex. 어노테이션을 통한 랜덤한 값 생성

간단한 예로 다음같이 사용할 수 있습니다.
다음 옵션을 추가하면 `String`을 생성할 때 마다 사람의 이름이 생성됩니다.
```kotlin
FixtureMonkey.builder()
    .pushExactTypeArbitraryIntrospector<String>(
                ArbitraryIntrospector {
                    Faker().name().firstName()
                }
            )
.build()
```

**Comment by KJongHyun** [comment]
@seongahjo 답변 감사합니다:)
