### ISSUE TITLE
Can not set final org.springframework.util.MultiValueMap field org.springframework.http.HttpHeaders.headers to java.util.HashMap

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#740]
## Describe the bug
`Can not set final org.springframework.util.MultiValueMap field org.springframework.http.HttpHeaders.headers to java.util.HashMap.`

This worked fine on 0.6.3. I think this happens due to the change to the final variables being now set.

## Your environment
* 0.6.5
* 17

## Steps to reproduce
https://github.com/esfomeado/fixture-monkey-bug/blob/master/src/test/java/com/example/bug/FixtureMonkeyTest.java#L80

## Expected behaviour
Should generate a `FilePart`

## Actual behaviour
Fails to generate a `FilePart`

**Comment by seongahjo** [comment]
@esfomeado 
It is fixed in 0.6.6.

Thank you!
