### ISSUE TITLE
Improve Documentation ver 2

### ISSUE THREAD

**Issue by SooKim1110** [naver/fixture-monkey#760]
Document Version 2 is now live at: https://naver.github.io/fixture-monkey/

The new document aims to be more user-friendly and is written in a more detailed manner compared to the previous version.

This issue lists some improvements that should be made to the document:

- [ ] Customize FlexSearch
- [x]  Fix design (homepage, fonts, color, etc.)
- [x] Fix the Release Notes page
- [ ] Add more examples in the options section
- [ ] Add Korean documentation
- [ ] Fix Code Highlight 
- [x] Fix thumbnail
- [x] Add cheetSheet
- [ ] upgrade to doks 1.0v
Feel free to share any ideas or report any issues that need fixing.

**Comment by seongahjo** [comment]
Add a new page for noticing supported complex types.

## Java
```java
@Value  
public class SelfReference {  
   String foo;  
   SelfReference bar;  
}  

@Value  
public class SelfReferenceList {  
   String foo;  
   List<SelfReferenceList> bar;  
}

public interface GenericInterface<T> {  
}  

@Value  
public static class GenericInterfaceImpl<T> implements GenericInterface<T> {
   T foo;  
}  

public interface TwoGenericInterface<T, U> {  
}  

@Value 
public static class TwoGenericImpl<T, U> implements TwoGenericInterface<T, U> {  
   T foo;  
  
   U bar;  
} 

@Value 
public static class GenericObject<T> {  
   T foo;  
}

@Value 
public static class GenericArrayObject<T> {  
   GenericObject<T>[] foo;  
}  
  
@Value 
public static class TwoGenericObject<T, U> {  
   T foo;  
   U bar;  
}  
  
@Value   
public static class ThreeGenericObject<T, U, V> {  
   T foo;  
   U bar;  
   V baz;  
}

public interface Interface {  
   String foo();  
  
   Integer bar();  
}

public interface InheritedInterface extends Interface {  
   String foo();  
}  
  
public interface InheritedInterfaceWithSameNameMethod extends Interface { 
   String foo();
}

public interface ContainerInterface {  
   List<String> baz();  
  
   Map<String, Integer> qux();  
}

public interface InheritedTwoInterface extends Interface, ContainerInterface { 
}

```

## Kotlin
```
```kotlin
class SelfReference(val foo: String, val bar: SelfReference?)

class Generic<T>(val foo: T)  
  
class GenericImpl(val foo: Generic<String>)

sealed class SealedClass  
  
object ObjectSealedClass : SealedClass()  
  
class SealedClassImpl(val foo: String) : SealedClass()

@JvmInline  
value class ValueClass(val foo: String)
```
```

**Comment by seongahjo** [comment]
Add `instantiate`, `instantiateBy`

**Comment by SooKim1110** [comment]
- [ ] Add document versioning

**Comment by seongahjo** [comment]
- [ ]  Add detailed information about the option. If it starts with "push" or "add", it can be nested.

**Comment by seongahjo** [comment]
- [ ] Add detailed information about that Fixture Monkey will use the canonical constructor if generating a record type with `ConstructorPropertiesArbitraryIntrospector`

**Comment by seongahjo** [comment]
- [ ] Add Fixture Monkey will generates non-printable characters by default in FAQ

**Comment by SooKim1110** [comment]
Closing this issue as it will be actively maintained in the Discussions page:

https://github.com/naver/fixture-monkey/discussions/858
https://github.com/naver/fixture-monkey/discussions/859
