### ISSUE TITLE
Fixture Monkey only copies some properties

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#782]
## Describe the bug
When using the `set` to set a value I expected all properties from the original object to be copied but sometimes isn't.

This was working fine on version 0.6.3 but it was broken after I tested with the latest version.

As a workaround I have to do `Values.just`.

## Your environment
* 0.6.10
* Java 17

## Steps to reproduce
https://github.com/esfomeado/fixture-monkey-bug/blob/master/src/test/java/com/example/bug/FixtureMonkeyTest.java#L99

## Expected behaviour
Should copy all properties like in 0.6.3

## Actual behaviour
It doesn't copy all properties

**Comment by seongahjo** [comment]
@esfomeado 
Thank you for your reporting an issue.
It is fixed in 0.6.11.
Please check it out.
Thank you.
