### ISSUE TITLE
Unable to generate Timestamp

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#786]
## Describe the bug
Unable to generate `Timestamp` due to no primary constructor

## Your environment
* 0.6.10
* Java 17

## Steps to reproduce
https://github.com/esfomeado/fixture-monkey-bug/blob/master/src/test/java/com/example/bug/FixtureMonkeyTest.java#L116

## Expected behaviour
Should generate  `Timestamp`

## Actual behaviour
It doesn't generate a  `Timestamp`

**Comment by seongahjo** [comment]
@esfomeado 
You can address this issue by using experimental feature `instantiate` in 0.6.12.

```java
Timestamp timestamp = fixtureMonkey.giveMeExperimentalBuilder(Timestamp.class)
            .instantiate(Instantiator.constructor())
            .sample();
```

You can use use `set` as well.

```java
Timestamp timestamp = fixtureMonkey.giveMeExperimentalBuilder(Timestamp.class)
			.instantiate(Instantiator.constructor()
				.parameter(Long.class, "time")
			)
			.set("time", 1L)
			.sample();
```
