### ISSUE TITLE
How to set custom JavaArbitaryResolver

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#819]
## Describe your question
I'm upgrading my project to version 1.0 of Fixture Monkey.
We use a custom `JavaArbitaryResolver`. 
Before I could set my custom arbitrary on the FixtureMonkey builder but now that doesn't seem possible.
How can I do that?
Thanks

Edit: Do I need to use the `JavaConstraintGenerator` instead?

**Comment by seongahjo** [comment]
@esfomeado 
Hello.  
`JavaArbitraryResolver` is still available. It is moved in `JqwikPlugin`.

If you do not have any custom annotations, `JavaConstraintGenerator` is an option too.
It removes a direct dependency from jqwik.

Thank you.

**Comment by esfomeado** [comment]
Sorry I think you misunderstood my question.

I'm aware that it moved packages but how do I set it on the FixtureMonkeyBuilder?

Thanks

**Comment by seongahjo** [comment]
@esfomeado 
You can set the option as shown below.
All options related to jqwik have moved as options of `JqwikPlugin`.

```
FixtureMonkey.builder()
	.plugin(
		new JqwikPlugin()
			.javaArbitraryResolver()
	)
```

Thank you  😁

**Comment by esfomeado** [comment]
Oh I see. Thanks ❤️
