### ISSUE TITLE
Unable to generate record where the construct calls a method from the parameter

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#822]
## Describe the bug
If a record construct calls a method from one of the parameters a NPE is thrown since the the parameter is null.

This use to work fine on 0.6.X but no longer works

## Your environment
Fixture Monkey 1.0.1
Java 17

## Steps to reproduce
https://github.com/esfomeado/fixture-monkey-bug/blob/a532641bb03aef4e0614ba7f0efcd9428f09388a/src/test/java/com/example/bug/FixtureMonkeyTest.java#L122

## Expected behaviour
Should generate the record

## Actual behaviour
The record is not generated

**Comment by seongahjo** [comment]
@esfomeado 
Thank you for reporting an issue.
It is fixed in 1.0.2!
Thank you.
