### ISSUE TITLE
NPE Cannot invoke "java.beans.ConstructorProperties.value()" 

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#839]
## Describe the bug
NPE when using a FailoverIntrospector

## Your environment
1.0.4
Java 17

## Steps to reproduce
https://github.com/esfomeado/fixture-monkey-bug/blob/master/src/test/java/com/example/bug/FixtureMonkeyTest.java

Run any test

## Expected behaviour
Should work without any exception

## Actual behaviour
NPE

**Comment by seongahjo** [comment]
@esfomeado 
Thank you for reporting an issue!
It is fixed in 1.0.5!
