### ISSUE TITLE
fixture monkey를 이용해서 객체 생성시 오류 문의

### ISSUE THREAD

**Issue by mygoaway** [naver/fixture-monkey#844]
## Describe the bug
*Describe your issue here.*
- Fixture Monkey를 이용해서 테스트용 객체 생성시, 생성하고자 하는 객체 내 MultipartFile 타입 값이 존재하는 경우 오류
- MultipartFile 타입의 값을 주석처리하는 경우, 정상적으로 객체 생성됩니다

## Your environment
* version of Fixture Monkey
* version of Java/Kotlin
- 자바 11버전

## Steps to reproduce
*Tell us how to reproduce this issue.*
*Or provide us an example repository to check the bug*

@Data
public class PayRequest {
    private MultipartFile file;
    private String linkUrl;
    private String email;
}

public class PayTest {

    private final FixtureMonkey fixtureMonkey = FixtureMonkey.builder()
            .objectIntrospector(FieldReflectionArbitraryIntrospector.INSTANCE)
            .build();

    @Test
    public void test() {
        PayRequest request = fixtureMonkey.giveMeBuilder(PayRequest.class)
                .set("linkUrl", "test")
                .sample();

        Assertions.assertThat(request.getLinkUrl()).isEqualTo("test");
    }
}

## Expected behaviour
*Tell us what should happen*
- 정상적으로 객체 생성 후 테스트 통과

## Actual behaviour
*Tell us what happens instead*
- 아래 메시지 출력
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.navercorp.fixturemonkey.api.type.TypeCache (file:/Users/1004794/.gradle/caches/modules-2/files-2.1/com.navercorp.fixturemonkey/fixture-monkey-api/1.0.0/10ea4216fcab386b114e1c1b7c165727ccd7f0/fixture-monkey-api-1.0.0.jar) to field java.io.File.path
WARNING: Please consider reporting this to the maintainers of com.navercorp.fixturemonkey.api.type.TypeCache
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

java.lang.NoSuchMethodException: java.io.File.<init>()

	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at com.navercorp.fixturemonkey.api.type.Reflections.newInstance(Reflections.java:41)
	at com.navercorp.fixturemonkey.api.introspector.FieldReflectionArbitraryIntrospector.lambda$introspect$0(FieldReflectionArbitraryIntrospector.java:58)

**Comment by seongahjo** [comment]
안녕하세요. @mygoaway 님

일단 원인부터 말씀드리면, 픽스쳐 몽키에서는 인터페이스가 입력되는 경우 자동으로 익명 객체를 생성해줍니다.
`MultipartFile` 내부에 `getResource` 메소드의 반환 값인 `Resource`를 생성하고, 
`Resource` 내부에 `getFile` 메소드의 반환 값인 File을 생성할 때 이슈가 발생합니다.

`File`은 빈 생성자가 존재하지 않아 `FieldReflectionArbitraryIntrospector` 으로는 생성할 수 없습니다. [문서 참조](https://naver.github.io/fixture-monkey/docs/generating-objects/introspector/#fieldreflectionarbitraryintrospector)


원하시는 의도에 따라 해결하는 방법이 달라질 것 같습니다. 

## MultipartFile가 필요가 없는 경우
```
private final FixtureMonkey fixtureMonkey = FixtureMonkey.builder()
        .objectIntrospector(FieldReflectionArbitraryIntrospector.INSTANCE)
        .pushAssignableTypeArbitraryIntrospector(
			MultipartFile.class,
			it -> new ArbitraryIntrospectorResult(CombinableArbitrary.from((Object)null))
         )
        .build();
```

## MultipartFile가 테스트에서 필요하고, 원하시는 구현체가 있는 경우
```
private final FixtureMonkey fixtureMonkey = FixtureMonkey.builder()
        .objectIntrospector(FieldReflectionArbitraryIntrospector.INSTANCE)
        .pushAssignableTypeArbitraryIntrospector(
			MultipartFile.class,
			it -> new ArbitraryIntrospectorResult(CombinableArbitrary.from(new MultipartFileImpl())
         )
        .build();
```

옵션 외에 연산을 사용해서 처리하실 수도 있는데, 필요하시면 말씀해주시면 방법을 공유드리겠습니다.
감사합니다.

**Comment by mygoaway** [comment]
아, 넵! 말씀주신대로 작업하니 문제없이 처리되네요.
추가적으로 한가지 더 질문드려도 괜찮을까요?
기존 자바 8에서는 문제 안되다가 최근 프로젝트를 자바 11버전으로 업그레이드한 이후 해당 문제가 발생했는데 혹시 해당 이유도 알 수 있을까요?

**Comment by seongahjo** [comment]
@mygoaway 
해결이 돼서 다행이네요 😄  혹시 자바11로 업그레이드하시면서 스프링 버전도 업그레이드 하셨을까요?
지금 문제가 된 메소드가 `spring-web` 5.1 버전 이후에 추가됐는데, 그 영향일 가능성이 커보입니다.

**Comment by mygoaway** [comment]
스프링 버전은 변경하지 않았습니다. 2.3.0 버전 사용중에 있습니다.

**Comment by seongahjo** [comment]
그럼 정확한 원인을 공유드리기는 어려울 것 같습니다.
일단 픽스쳐 몽키에서는 multi release가 적용이 되있어서 JDK 버전마다 동작이 달라지긴 하는데요, JDK 17에만 대응하고 있습니다.
JDK11에서는 동작이 다르지 않습니다.

제 추측을 말씀드리면, JDK 버전이 변경되면서 리플렉션 동작이 달라져서 생긴 이슈일 것 같다는 생각이 듭니다.
JDK vendor마다 리플렉션 구현이 조금씩 다르다고 알고 있습니다. 실제로 리플렉션을 통해 조회한 생성자, 메소드 순서가 JDK vendor마다 다릅니다.

**Comment by mygoaway** [comment]
넵, 저도 버전 변경에 따른 리플렉션이 원인이 아닐까?라는 추측은 하긴하였습니다.
여튼 해결책 빨리 말씀주셔서 감사합니다.
