### ISSUE TITLE
Make the API to use a javaGetter neater

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#849]
## Describe the feature you request
As of now in Java you can use getters to set a value as specified on the documentation.

```
    Order actual = sut.giveMeBuilder(Order.class)
            .set(javaGetter(Order::getOrderNo), "1")
            .set(javaGetter(Order::getProductName), "Line Sally")
            .minSize(javaGetter(Order::getItems), 1)
            .sample();
```

I think that it´s to verbose and not as neat as Kotlin where you can just do `.setExp(Order::orderNo, "1")`.

I suggest to be a similar syntax as well for Java users.

**Comment by seongahjo** [comment]
@esfomeado 
Thanks for the suggestion.  Do you have any good ideas?

Do you want an API that looks like this?
```java
Order actual = sut.giveMeBuilder(Order.class)
    .setExpGetter(Order::getOrderNo, 1)
    .sample();
````

**Comment by esfomeado** [comment]
That looks good to me.

**Comment by seongahjo** [comment]
@esfomeado 
Hello, thank you for waiting.

Finally, 1.1.0 has been released. Please check it out!
