### ISSUE TITLE
Java 8 is not supported

### ISSUE THREAD

**Issue by praveenfun2** [naver/fixture-monkey#851]
## Describe the bug
As mentioned in the official documentation, fixture-monkey should support Java 8 / kotlin 1.8 but I am getting issues while using in a project with Kotlin 1.8.

## Your environment
* com.navercorp.fixturemonkey:fixture-monkey-starter-kotlin:1.0.5
* kotlinVersion=1.8.22
* java 1.8 & JRE 17

## Steps to reproduce
*Use the above environment setup

## Expected behaviour
*gradle lockdown should work without errors*

## Actual behaviour
*Gradle lockdown failed with the below error*
> Execution failed for task ':pug-client:lockdown'.
  Could not resolve all dependencies for configuration ':pug-client:tmp-lockdown-check-testRuntimeClasspath'.
   > Could not resolve com.navercorp.fixturemonkey:fixture-monkey-starter-kotlin:1.0.5.
     Required by:
         project :pug-client > project :pug-core-testutils
      > No matching variant of com.navercorp.fixturemonkey:fixture-monkey-starter-kotlin:1.0.5 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
          - Variant 'apiElements' capability com.navercorp.fixturemonkey:fixture-monkey-starter-kotlin:1.0.5 declares a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
          - Variant 'javadocElements' capability com.navercorp.fixturemonkey:fixture-monkey-starter-kotlin:1.0.5 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
          - Variant 'runtimeElements' capability com.navercorp.fixturemonkey:fixture-monkey-starter-kotlin:1.0.5 declares a runtime of a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
          - Variant 'sourcesElements' capability com.navercorp.fixturemonkey:fixture-monkey-starter-kotlin:1.0.5 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')

**Comment by seongahjo** [comment]
@praveenfun2 
Thank you for reporting an issue.
It would be fixed in 1.0.7.
I'll let you know when it is published.

**Comment by praveenfun2** [comment]
Unfortunately, our organization uses a private repository & this snapshot is not available there. Will wait for the release. Thanks.

**Comment by seongahjo** [comment]
@praveenfun2 
Oh, I see. 1.0.7 is released.

**Comment by praveenfun2** [comment]
Seems to be working now..!!

**Comment by praveenfun2** [comment]
This can be closed
