### ISSUE TITLE
Stop generating random values

### ISSUE THREAD

**Issue by praveenfun2** [naver/fixture-monkey#863]
## Describe your question
*Is there a way by which we can disable prepopulating the fields with random values.*

**Comment by seongahjo** [comment]
@praveenfun2 
Hello, it would be great with a detailed example. Is it for a specific test case or all test cases?

There are several ways to disable pre-population. Here are some common ways you can handle this issue.

1. `set` API in ArbitraryBuilder would prevent the generation of a random value.
It will work in all test cases if you use this API in `register` option.
2. You can use [`pushArbitraryIntrospector` option](https://naver.github.io/fixture-monkey/docs/fixture-monkey-options/generation-options/#arbitraryintrospector)
3. You can use [`pushPropertyGenerator` option](https://naver.github.io/fixture-monkey/docs/fixture-monkey-options/generation-options/#propertygenerator) to remove the properties that are not random values. But in this case, you can not use `set` API.

**Comment by seongahjo** [comment]
@praveenfun2 
If so, you can use `defaultNullInjectGenerator` option.

```java
FixtureMonkey nullGenerateFixtureMonkey = FixtureMonkey.builder()
			.defaultNullInjectGenerator(
				new DefaultNullInjectGenerator(
					1.0d,
					false,
					false,
					false,
					Collections.emptySet(),
					Collections.emptySet()
				)
			)
			.build();
```

`nullGenerateFixtureMonkey` will generate all properties as null if you do not use any customization APIs.

Or You can use your existing test setup just as below.

```
fixtureMonkey.giveMeBuilder(YourExistingTestObject)
    .sample()
```

FixtureMonkey instance will generate an object exactly like your existing test object, without populating it with random values.
You can customise it just like any other instance Fixture Monkey generates.

**Comment by seongahjo** [comment]
Let me know if any more questions!
