### ISSUE TITLE
FixtureMonkey in Kotlin (sealed class + object)

### ISSUE THREAD

**Issue by kdohyeon** [naver/fixture-monkey#867]
## Describe your question
*Tell us what kind of problem you are having.*

I am having difficulty applying FixtureMonkey with Kotlin's sealed class and object.

Please consider the below code:

- We have a sealed class and an object extending the sealed class.

```kotlin
sealed class SealedClassA(
  val valueA: String,
  val valueB: String,
) {
  object OBJECTA : SealedClassA(
    valueA = "123",
    valueB = "456"
  )
}
```

- There is a data class that contains SealedClassA.

```kotlin
data class DataClassA(
  val sealedClassA: SealedClassA
)
```

- I would like to make a mock data for DataClassA.

```kotlin
val fixtureMonkey = FixtureMonkey.builder().plugins(KotlinPlugin()).build()

val mockData = fixtureMonkey.giveMeBuilder<DataClassA>().sample()
```

- When I try to make a mock data containing a sealed class and an object, then it keeps throwing an error, saying:

```
bound must be positive
```

Did I miss out some configs? Anybody faced some similuar issue like this?

Any kind of help would be really appreciated.

Thank you!

**Comment by seongahjo** [comment]
@kdohyeon 
Hello. Currently, `object` inheriting a sealed class is not supported, as it is a constant that does not need to populate random properties.

There is an alternative way to generate it.

```
 FixtureMonkey.builder()
                .plugin(KotlinPlugin())
                .pushAssignableTypeObjectPropertyGenerator<SealedClassA> { context ->
                    InterfaceObjectPropertyGenerator(listOf(SealedClassA.OBJECTA::class.java))
                        .generate(context)
                }
                .pushAssignableTypeArbitraryIntrospector<SealedClassA> {
                    ArbitraryIntrospectorResult(
                        CombinableArbitrary.from(SealedClassA.OBJECTA),
                    )
                }
                .build()
```

It will be supported in version 1.1.0.

Thank you.

**Comment by kdohyeon** [comment]
Oh, thank you for the guide code.

It works well. 👍
