### ISSUE TITLE
Unable to set list value

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#881]
## Describe the bug
After updating to 1.0.10 I'm now unable to set the value of lists. Sometimes is set to `null` other time it's set to something random and not to the value provided.
This change was introduced on 1.0.10

## Your environment
* 1.0.10
* Java 17

## Steps to reproduce
https://github.com/esfomeado/fixture-monkey-bug/blob/master/src/test/java/com/example/bug/FixtureMonkeyTest.java#L133

## Expected behaviour
I should be able to set the list value like before

## Actual behaviour
The value is set to null or something random.

**Comment by esfomeado** [comment]
@seongahjo Sorry you are right but I have a new bug on 1.0.10 where in some scenarios that value that is set is different from the one provided. I will try to create a replication.

**Comment by esfomeado** [comment]
I was finally able to reproduce the issue. You can check the same reproduction.

https://github.com/esfomeado/fixture-monkey-bug/blob/master/src/test/java/com/example/bug/FixtureMonkeyTest.java#L136

What happens is that Fixture Monkey generates objects again if they are of the same time.

**Comment by seongahjo** [comment]
@esfomeado 
Thank you for reproducing the issue!
It is fixed in `1.0.11`. Please check it out.

**Comment by esfomeado** [comment]
Fixed. Thanks
