### ISSUE TITLE
Error while generating class where constructor as different types from parent

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#907]
## Describe the bug
When generating class where constructor as different types from parent an exception is thrown.

java.lang.IllegalArgumentException: argument type mismatch

## Your environment
* 1.0.12
* Java 17

## Steps to reproduce
https://github.com/esfomeado/fixture-monkey-bug/blob/master/src/test/java/com/example/bug/FixtureMonkeyTest.java#L153

## Expected behaviour
Should generate the class correctly

## Actual behaviour
Exception is thrown

**Comment by seongahjo** [comment]
@esfomeado 
Hello, thank you for reporting an issue.
It is fixed in 1.0.13. Please check it out!
