### ISSUE TITLE
ask; Setting Super Class Property Values in Kotlin

### ISSUE THREAD

**Issue by xeromank** [naver/fixture-monkey#926]
## Describe your question
*Tell us what kind of problem you are having.*
Hello. 
I forked the code and saw it, 
To set the value of a property in a super class in Kotlin, 
and it seems that I need to use KotlinPlugin() and JacksonPlugin(). 
Is that correct?

I wish I don't use JacksonPlugin().
Is it possilble?

![image](https://github.com/naver/fixture-monkey/assets/81915068/cc6d00e0-179e-4a0e-9cf1-533be2876572)

**Comment by seongahjo** [comment]
@xeromank 
It is possible. All you need is the `CompositeArbitraryIntrospector`

```kotlin
FixtureMonkey.builder()
      .plugin(KotlinPlugin())
      .objectIntrospector(
          CompositeArbitraryIntrospector(
              listOf(
                  PrimaryConstructorArbitraryIntrospector.INSTANCE,
                  FieldReflectionArbitraryIntrospector.INSTANCE
              )
      )
  )
  .build()
```

Let me know if you have any problems.

**Comment by xeromank** [comment]
@seongahjo
Thanks to you, it's going really well.
