### ISSUE TITLE
Minor bugs on the newly added translated docs

### ISSUE THREAD

**Issue by fingersdanny** [naver/fixture-monkey#957]
## Describe the bug
* When you change the langauge (English to Korean) on the main page and click on the ``Get Started`` button, it takes to the original English version of the document.
* When selecting different language while on the docs page, it leads to the main page.

## Your environment
* Tested Browser : Chrome

## Steps to reproduce
* Regarding ``Get Started`` button
![image](https://github.com/naver/fixture-monkey/assets/54776553/397d55c6-9431-4aa4-8423-cf1b035e19c5)
![image](https://github.com/naver/fixture-monkey/assets/54776553/1ab0ed25-fd9d-4f2b-8a32-73212b5777b4)

* Regarding selecting different language
![image](https://github.com/naver/fixture-monkey/assets/54776553/f5c2bd17-7c20-4a31-b2ac-e33c4c2740a4)
![image](https://github.com/naver/fixture-monkey/assets/54776553/db80a507-58cc-4a83-a151-fe131cbfc266)
![image](https://github.com/naver/fixture-monkey/assets/54776553/f2b290d1-d770-454b-9f42-5648c812cd35)

## Expected behaviour
* ``Get Started`` button leads to the translated version of the document
* when the language is changed while on the docs page, it stays on the same page but with the selected language. 

## Actual behaviour
* Actual behaviors are as mentioned in the ``Describe the bug`` section

**Comment by SooKim1110** [comment]
Thanks for the report! Fixed in #959
