### ISSUE TITLE
Class changes when setting value

### ISSUE THREAD

**Issue by esfomeado** [naver/fixture-monkey#958]
## Describe your question

I´ve created this as question because I wasn´t sure if this is the intended behavior.

https://github.com/esfomeado/fixture-monkey-bug/blob/e4d3128a4cb798fff7ed6aa3c4c8b64d15ba68f3/src/test/java/com/example/bug/FixtureMonkeyTest.java#L171

On this test I have two class. `A` and `B`.

I then I create a `B` object and set it on the Alphabet. The issue is that the class will change from B to A sometimes.

If I use the `Values.just` it works but I would except to use the same class type as the one that I pass in and not another subtype.

Thanks

**Comment by seongahjo** [comment]
@esfomeado 
Hello, it is unintentional. It is actually a bug.

I'll fix it in 1.0.15

**Comment by seongahjo** [comment]
@esfomeado 
Thanks for waiting. 1.0.15 is released. 
Please check if it is fixed.

**Comment by esfomeado** [comment]
It's fixed. Thanks
