### ISSUE TITLE
I want fields to be injected with a Kotlin Duration type

### ISSUE THREAD

**Issue by this-is-spear** [naver/fixture-monkey#962]
## Describe the feature you request
The user doesn't understand why the field needs to be injected with the `Long` type.

``` kotlin
sut.giveMeBuilder<DurationValue>()
    .set(DurationValue::duration, Long.MAX_VALUE)
    .sample()
```

## Suggest A Solution

For ease of use, Duration needs to be modified to allow you to inject Duration values.

``` kotlin
sut.giveMeBuilder<DurationValue>()
    .set(DurationValue::duration, Duration.INFINITE)
    .sample()
```

## If the feature request is approved, would you be willing to submit a PR?
*Yes*

**Comment by seongahjo** [comment]
@this-is-spear 
Sounds great.  Could you make a PR for it?

**Comment by this-is-spear** [comment]
Okay, good!
