### ISSUE TITLE
1.0.17 버전에서 SimpleValueJqwikPlugin 사용시 Set<Integer> 의 임의값이 생성되지 않습니다.

### ISSUE THREAD

**Issue by junyoung-kang-kurly** [naver/fixture-monkey#986]
## Describe the bug
SimpleValueJqwikPlugin 사용시 Set<Integer> 유형에 2개이상 엘리먼트에 할당되도록 했을시, sample 객체 생성이 완료되지 못하고 무한루프 하고 있습니다.

## Your environment
* version of Fixture Monkey : 1.0.17 + SimpleValueJqwikPlugin
* version of Java/Kotlin : 1.8, 11, 17

## Steps to reproduce
```java
public class TestObject {

	private Set<Integer> integers;

	public Collection<Integer> getIntegers() {
		return integers;
	}
}
```

```java
public class SampleCreatingFailureTest {

	@Property(tries = 10)
	void test() {
		// given
		FixtureMonkey sut = FixtureMonkey.builder()
			.objectIntrospector(FieldReflectionArbitraryIntrospector.INSTANCE)
			.plugin(new SimpleValueJqwikPlugin())
			.build();

		// when  - sample 객체가 생성되지 않고 무한루프 합니다.
		TestObject actual = sut.giveMeBuilder(TestObject.class)
			.size("integers", 2)
			.sample();

		// then
		then(actual).isNotNull();
		then(actual.getIntegers()).hasSize(2);
	}
}
```

## Expected behaviour
`Set<Integer> integers` 필드에 2개의 엘리먼트에 임의 값들이 할당되어야 합니다.

## Actual behaviour
하지만 무한루프와 함께 할당이 되지 않고 객체생성이 되지 않아 .sample() 다음 라인으로 진행되지 않습니다.

아래 조치중 하나를 하면 정상 동작하고 있습니다.
1. 엘리먼트를 1개 이하로 생성되도록 변경 (예: `.size("integers", 1)` 로 변경)
2. integers 필드 유형을 Set에서 List로 변경
3. `Set<Integer>` 의 제네릭을 Number가 아닌 유형으로 변경. (예: `Set<String>`)
4. SimpleValueJqwikPlugin 플러그인을 제거

**Comment by seongahjo** [comment]
@junyoung-kang-kurly 
1.0.18에서 해결됐습니다! 감사합니다~
