### ISSUE TITLE
Print seed if test fails in JUnit

### ISSUE THREAD

**Issue by seongahjo** [naver/fixture-monkey#990]
## Describe the feature you request
It is hard to generate a same instance of a type in Fixture Monkey, because it generates an arbitrary instance of the type.
But if you use a same seed, you can easily reproduce a same instance of the type.

Fixture Monkey now supports the `seed` option as shown below.

```kotlin
  FixtureMonkey.builder()
            .seed(XXXX)
            .build()
```

The problem is that we do not know what the seed is.
Fixture Monkey needs a way to print seed if the test fails.
It needs the support of a test framework, JUnit.

## Suggest A Solution
Add an JUnit Extension implements `AfterTestExecutionCallback` interface that prints the seed if the test fails.

**Comment by codesejin** [comment]
Hello, I'm interested in this open-source project. If this issue hasn't been addressed yet, may I take a shot at solving it?

**Comment by seongahjo** [comment]
@codesejin 
Sure. Please let me know if you have any problems in resolving this.

**Comment by seongahjo** [comment]
@codesejin 
Hello, are there any updates?
