### ISSUE TITLE
kotlin Lambda 함수 사용할 수 있는법 

### ISSUE THREAD

**Issue by Ibodwe** [naver/fixture-monkey#996]
## Describe your question
*Tell us what kind of problem you are having.*

data class TestKotlinClass(
    val test: (String, String, String) -> Unit = { _, _ ,_ -> },
) 
위 함수를 설정하고 

 val t = fixture.giveMeBuilder(TestKotlinClass::class.java)
            .set(TestKotlinClass::test , {})
            .sample() 
            
 fixture를 만들면 다음과 같은 에러가 발생하는데 Lambda 함수를 사용해서 만들 수는 없는걸까요?? 
 
 Unknown origin of public abstract operator fun invoke(p1: P1, p2: P2, p3: P3): R defined in kotlin.Function3[FunctionInvokeDescriptor@184dbacc] (class kotlin.reflect.jvm.internal.impl.builtins.functions.FunctionInvokeDescriptor)

**Comment by seongahjo** [comment]
@Ibodwe 
안녕하세요.

현재 1.0.21에서 지원하는 람다는 자바의 `Supplier`입니다. 
코틀린 람다를 포함한 람다는 지원하지 않고 있고, 1.0.22부터 지원할 예정입니다.

1.0.22 이전 버전에서 문의 주신 케이스를 다음과 같은 옵션을 설정해서 해결할 수 있습니다.

```kotlin
data class TestKotlinClass(
    val test: (String, String, String) -> Unit,
)

  val expected: (String, String, String) -> Unit = { _, _, _ -> }

  // when
  val actual: TestKotlinClass = FixtureMonkey.builder()
      .plugin(KotlinPlugin())
      .pushAssignableTypePropertyGenerator(Function::class.java) { listOf() }
      .build()
      .giveMeBuilder<TestKotlinClass>()
      .setExp(TestKotlinClass::test, Values.just(expected))
      .sample()

  then(actual.test).isNotNull
```

혹시 해결이 안되시면 말씀해주세요.
감사합니다.

**Comment by Ibodwe** [comment]
> @Ibodwe 안녕하세요.
> 
> 현재 1.0.21에서 지원하는 람다는 자바의 `Supplier`입니다. 코틀린 람다를 포함한 람다는 지원하지 않고 있고, 1.0.22부터 지원할 예정입니다.
> 
> 1.0.22 이전 버전에서 문의 주신 케이스를 다음과 같은 옵션을 설정해서 해결할 수 있습니다.
> 
> ```kotlin
> data class TestKotlinClass(
>     val test: (String, String, String) -> Unit,
> )
> 
>   val expected: (String, String, String) -> Unit = { _, _, _ -> }
> 
>   // when
>   val actual: TestKotlinClass = FixtureMonkey.builder()
>       .plugin(KotlinPlugin())
>       .pushAssignableTypePropertyGenerator(Function::class.java) { listOf() }
>       .build()
>       .giveMeBuilder<TestKotlinClass>()
>       .setExp(TestKotlinClass::test, Values.just(expected))
>       .sample()
> 
>    then(actual.test).isEqualTo(expected)
> ```
> 
> 혹시 해결이 안되시면 말씀해주세요. 감사합니다.

답변 감사합니다! 해결 되었습니다!!

**Comment by seongahjo** [comment]
@Ibodwe 
안녕하세요. 1.0.22가 배포됐습니다.
1.0.22 부터는 코틀린 람다 함수 생성을 기본적으로 지원합니다.

```kotlin
@Test
    fun kotlinLambda() {
        // given
        class KotlinLambdaValue(val lambda: (String, String, String) -> Unit)

        // when
        val actual: KotlinLambdaValue = SUT.giveMeOne()

        then(actual.lambda).isNotNull
    }
```

감사합니다.
